name: cloud-one
pipeline:
  - name: parsed_event
    external:
      name: cef.parse-cef

  - name: set_extract_fields

stages:
  set_extract_fields:
    actions:
      - set:
          event.reason: '{{parsed_event.message.msg}}'
          user.name: '{{parsed_event.message.suser}}'
          source.ip: '{{parsed_event.message.src}}'
          source.user.name: '{{parsed_event.message.suser}}'
          user.target.name: '{{parsed_event.message.target}}'
#
#      - translate:
#        dictionary:
#          "10": "Custom Intrusion Prevention (IPS) rule"
#          "20": "Log-only Firewall rule"
#          "21": "Deny Firewall rule"
#          "30": "Custom Integrity Monitoring rule"
#          "40": "Custom Log Inspection rule"
#          "100-7499": "System events"
#          "100-199": "Policy Firewall rule and Firewall stateful configuration"
#          "200-299": "IPS internal errors"
#          "300-399": "SSL/TLS events"
#          "500-899": "IPS normalization"
#          "1,000,000-1,999,999": "Trend Micro IPS rule. The signature ID is the same as the IPS rule ID."
#          "2,000,000-2,999,999": "Integrity Monitoring rule. The signature ID is the Integrity Monitoring rule ID + 1,000,000."
#          "3,000,000-3,999,999": "Log Inspection rule. The signature ID is the Log Inspection rule ID + 2,000,000."
#          "4,000,000-4,999,999": "Anti-Malware events. Currently, only these signature IDs are used:"
#          "4,000,000": "Anti-Malware - Real-Time Scan"
#          "4,000,001": "Anti-Malware - Manual Scan"
#          "4,000,002": "Anti-Malware - Scheduled Scan"
#          "4,000,003": "Anti-Malware - Quick Scan"
#          "4,000,010": "Anti-Spyware - Real-Time Scan"
#          "4,000,011": "Anti-Spyware - Manual Scan"
#          "4,000,012": "Anti-Spyware - Scheduled Scan"
#          "4,000,013": "Anti-Spyware - Quick Scan"
#          "4,000,020": "Suspicious Activity - Real-Time Scan"
#          "4,000,030": "Unauthorized Change - Real-Time Scan"
#          "5,000,000": "Web Reputation - Blocked"
#          "5,000,001": "Web Reputation - Detect Only"
#          "6,001,100": "Application Control - Detect Only, in block list"
#          "6,001,200": "Application Control - Detect Only, not in allow list"
#          "6,002,100": "Application Control - Blocked, in block list"
#          "6,002,200": "Application Control – Blocked, not in allow list"
#          "7,000,000": "Device Control - access unknown device was blocked"
#          "7,000,200": "Device Control - write unknown device was blocked"
#          "7,001,000": "Device Control - access USB device was blocked"
#          "7,001,200": "Device Control - write USB device was blocked"
#          "7,002,000": "Device Control - access mobile device was blocked"
#          "7,002,200": "Device Control - write mobile device was blocked"
#        mapping:
#          parsed_event.message.get('Signature ID'): event.reason

