name: cloud-one
pipeline:
  - name: parsed_event
    external:
      name: cef.parse-cef

  - name: set_extract_fields

stages:
  set_extract_fields:
    actions:
      - set:
          event.reason: '{{parsed_event.message.msg}}'
          user.name: '{{parsed_event.message.suser}}'
          source.ip: '{{parsed_event.message.src}}'
          source.user.name: '{{parsed_event.message.suser}}'
          user.target.name: '{{parsed_event.message.target}}'