name: sentinelone
pipeline:
  - name: json_event
    external:
      name: json.parse-json
      properties:
        input_field: "{{original.message}}"
  - name: read_agent_info
  - name: read_threat_info
    
stages:

  read_agent_info:
    actions:
    - set:
        organization.id: "{{json_event.message.agentRealtimeInfo.accountId}}"
        organization.name: "{{json_event.message.agentRealtimeInfo.accountName}}"
        sentinelone.sitename: "{{json_event.message.agentDetectionInfo.siteName}}"
        sentinelone.groupname: "{{json_event.message.agentDetectionInfo.groupName}}"
        sentinelone.eventid: "{{json_event.message.id}}"

        host.os.version: "{{json_event.message.agentRealtimeInfo.agentOsName}}"
        host.os.family: "{{json_event.message.agentRealtimeInfo.agentOsType}}"
        host.domain: "{{json_event.message.agentDetectionInfo.agentDomain}}"
        host.ip:
          - "{{json_event.message.agentDetectionInfo.agentIpV4}}"
          - "{{json_event.message.agentDetectionInfo.agentIpV6}}"
          - "{{json_event.message.agentDetectionInfo.externalIp}}"
        
        sentinelone.agentDetectionInfo.agentLastLoggedInUserName: "{{json_event.message.agentDetectionInfo.agentLastLoggedInUserName}}"
        sentinelone.agentDetectionInfo.mitigationStatus: "{{json_event.message.agentDetectionInfo.agentLastLoggedInUserName}}"

  read_threat_info:
    actions:
    - set:
        sentinelone.threatInfo.analystVerdict: "{{json_event.message.threatInfo.analystVerdict}}"
        sentinelone.threatInfo.analystVerdictDescription: "{{json_event.message.threatInfo.analystVerdictDescription}}"
        sentinelone.threatInfo.AuthenticationPackageName: "{{json_event.message.threatInfo.AuthenticationPackageName}}"
        sentinelone.threatInfo.automaticallyResolved: "{{json_event.message.threatInfo.automaticallyResolved}}"
        sentinelone.threatInfo.browserType: "{{json_event.message.threatInfo.browserType}}"
        sentinelone.threatInfo.certificateId: "{{json_event.message.threatInfo.certificateId}}"
        sentinelone.threatInfo.classification: "{{json_event.message.threatInfo.classification}}"
        sentinelone.threatInfo.classificationSource: "{{json_event.message.threatInfo.classificationSource}}"
        sentinelone.threatInfo.cloudFilesHashVerdict: "{{json_event.message.threatInfo.cloudFilesHashVerdict}}"
        sentinelone.threatInfo.confidenceLevel: "{{json_event.message.threatInfo.confidenceLevel}}"        
        sentinelone.threatInfo.createdAt: "{{json_event.message.threatInfo.createdAt}}"
        sentinelone.threatInfo.detectionType: "{{json_event.message.threatInfo.detectionType}}"        
        sentinelone.threatInfo.failedActions: "{{json_event.message.threatInfo.failedActions}}"

        file.extension: "{{json_event.message.threatInfo.fileExtension|lower}}"
        file.path: "{{json_event.message.threatInfo.filePath}}"
        file.size: "{{json_event.message.threatInfo.fileSize}}"
                
        
