name: sentinelone
pipeline:
  - name: json_event
    external:
      name: json.parse-json
      properties:
        input_field: "{{original.message}}"
  - name: read_threat_info
  - name: read_agent_info
  - name: read_agent_detection_info
    filter: '{{json_event.message.agentRealtimeInfo != null }}'
  - name: read_agent_realtime_info
    filter: '{{json_event.message.agentDetectionInfo != null }}'
  - name: read_data
    filter: '{{json_event.message.data != null }}'

stages:
  read_agent_info:
    actions:
    - set:
        sentinelone.eventid: "{{json_event.message.id}}"
        organization.id: "{{json_event.message.accountId}}"
        organization.name: "{{json_event.message.accountName}}"
        action.type: "{{json_event.message.activityType}}"
        user.id: "{{json_event.message.userId}}"
        sentinelone.primaryDescription: "{{json_event.message.primaryDescription}}"
        sentinelone.secondaryDescription: "{{json_event.message.secondaryDescription}}"
        sentinelone.siteId: "{{json_event.message.siteId}}"
        sentinelone.description: "{{json_event.message.description}}"
        sentinelone.groupId: "{{json_event.message.groupId}}"
        sentinelone.groupname: "{{json_event.message.groupName}}"
        sentinelone.hash: "{{json_event.message.hash}}"
        sentinelone.agentId: "{{json_event.message.agentId}}"
        sentinelone.agentUpdatedVersion: "{{json_event.message.agentUpdatedVersion}}"
        sentinelone.comments: "{{json_event.message.comments}}"
        sentinelone.sitename: "{{json_event.message.siteName}}"
        sentinelone.threatId: "{{json_event.message.threatId}}"
        sentinelone.updatedAt: "{{json_event.message.updatedAt}}"
        os.family: "{{json_event.message.osFamily}}"

  read_data:
    actions:
    - set:
        sentinelone.data.accessPermissionsentinelone.data.: "{{json_event.message.data.accessPermission}}"
        sentinelone.data.action: "{{json_event.message.data.action}}"
        sentinelone.data.activatedEngines: "{{json_event.message.data.activatedEngines}}"
        sentinelone.data.bluetoothAddress: "{{json_event.message.data.bluetoothAddress}}"
        sentinelone.data.byUser: "{{json_event.message.data.byUser}}"
        sentinelone.data.computerName: "{{json_event.message.data.computerName}}"
        sentinelone.data.current: "{{json_event.message.data.current}}"
        sentinelone.data.deviceClass: "{{json_event.message.data.deviceClass}}"
        sentinelone.data.deviceInformationServiceInfoKey: "{{json_event.message.data.deviceInformationServiceInfoKey}}"
        sentinelone.data.deviceInformationServiceInfoValue: "{{json_event.message.data.deviceInformationServiceInfoValue}}"
        sentinelone.data.deviceName: "{{json_event.message.data.deviceName}}"
        sentinelone.data.deactivatedEngines: "{{json_event.message.data.deactivatedEngines}}"
        sentinelone.data.disabledLevel: "{{json_event.message.data.disabledLevel}}"
        sentinelone.data.downloadUrl: "{{json_event.message.data.downloadUrl}}"
        sentinelone.data.enabledReason: "{{json_event.message.data.enabledReason}}"
        sentinelone.data.exclusionType: "{{json_event.message.data.exclusionType}}"
        sentinelone.data.expiration: "{{json_event.message.data.expiration}}"
        sentinelone.data.externalIp: "{{json_event.message.data.externalIp}}"
        sentinelone.data.fileContentHash: "{{json_event.message.data.fileContentHash}}"
        sentinelone.data.filename: "{{json_event.message.data.filename}}"
        sentinelone.data.filePath: "{{json_event.message.data.filePath}}"
        sentinelone.data.fullScopeDetails: "{{json_event.message.data.fullScopeDetails}}"
        sentinelone.data.gattService: "{{json_event.message.data.gattService}}"
        sentinelone.data.interface: "{{json_event.message.data.interface}}"
        sentinelone.data.lmpVersion: "{{json_event.message.data.lmpVersion}}"
        sentinelone.data.manufacturerName: "{{json_event.message.data.manufacturerName}}"
        sentinelone.data.minorClasses: "{{json_event.message.data.minorClasses}}"
        sentinelone.data.order: "{{json_event.message.data.order}}"
        sentinelone.data.policy: "{{json_event.message.data.policy}}"
        sentinelone.data.policyName: "{{json_event.message.data.policyName}}"
        sentinelone.data.previous: "{{json_event.message.data.previous}}"
        sentinelone.data.productId: "{{json_event.message.data.productId}}"
        sentinelone.data.profileUuids: "{{json_event.message.data.profileUuids}}"
        sentinelone.data.reason: "{{json_event.message.data.reason}}"
        sentinelone.data.role: "{{json_event.message.data.role}}"
        sentinelone.data.ruleId: "{{json_event.message.data.ruleId}}"
        sentinelone.data.ruleName: "{{json_event.message.data.ruleName}}"
        sentinelone.data.rulename: "{{json_event.message.data.rulename}}"
        sentinelone.data.ruleType: "{{json_event.message.data.ruleType}}"
        sentinelone.data.scopeLevel: "{{json_event.message.data.scopeLevel}}"
        sentinelone.data.scopeName: "{{json_event.message.data.scopeName}}"
        sentinelone.data.scopeId: "{{json_event.message.data.scopeId}}"
        sentinelone.data.shouldReboot: "{{json_event.message.data.shouldReboot}}"
        sentinelone.data.source: "{{json_event.message.data.source}}"
        sentinelone.data.status: "{{json_event.message.data.status}}"
        sentinelone.data.uid: "{{json_event.message.data.uid}}"
        sentinelone.data.uploadedFilename: "{{json_event.message.data.uploadedFilename}}"
        sentinelone.data.uuid: "{{json_event.message.data.uuid}}"
        sentinelone.data.username: "{{json_event.message.data.username}}"
        sentinelone.data.userName: "{{json_event.message.data.userName}}"
        sentinelone.data.userId: "{{json_event.message.data.userId}}"
        sentinelone.data.userscope: "{{json_event.message.data.userscope}}"
        sentinelone.data.vendorId: "{{json_event.message.data.vendorId}}"
        sentinelone.data.version: "{{json_event.message.data.version}}"
        sentinelone.data.setting: "{{json_event.message.data.setting}}"
        sentinelone.data.alertId: "{{json_event.message.data.alertId}}"
        sentinelone.data.detectedat: "{{json_event.message.data.detectedat}}"
        sentinelone.data.dveventid: "{{json_event.message.data.dveventid}}"
        sentinelone.data.dveventtype: "{{json_event.message.data.dveventtype}}"
        sentinelone.data.groupName: "{{json_event.message.data.groupName}}"
        sentinelone.data.k8sclustername: "{{json_event.message.data.k8sclustername}}"
        sentinelone.data.k8scontainerid: "{{json_event.message.data.k8scontainerid}}"
        sentinelone.data.k8scontainerimage: "{{json_event.message.data.k8scontainerimage}}"
        sentinelone.data.k8scontainerlabels: "{{json_event.message.data.k8scontainerlabels}}"
        sentinelone.data.k8scontainername: "{{json_event.message.data.k8scontainername}}"
        sentinelone.data.k8scontrollerkind: "{{json_event.message.data.k8scontrollerkind}}"
        sentinelone.data.k8scontrollerlabels: "{{json_event.message.data.k8scontrollerlabels}}"
        sentinelone.data.k8scontrollername: "{{json_event.message.data.k8scontrollername}}"
        sentinelone.data.k8snamespace: "{{json_event.message.data.k8snamespace}}"
        sentinelone.data.k8snamespacelabels: "{{json_event.message.data.k8snamespacelabels}}"
        sentinelone.data.k8snode: "{{json_event.message.data.k8snode}}"
        sentinelone.data.k8spod: "{{json_event.message.data.k8spod}}"
        sentinelone.data.k8spodlabels: "{{json_event.message.data.k8spodlabels}}"
        sentinelone.data.origagentmachinetype: "{{json_event.message.data.origagentmachinetype}}"
        sentinelone.data.origagentname: "{{json_event.message.data.origagentname}}"
        sentinelone.data.origagentosfamily: "{{json_event.message.data.origagentosfamily}}"
        sentinelone.data.origagentosname: "{{json_event.message.data.origagentosname}}"
        sentinelone.data.origagentosrevision: "{{json_event.message.data.origagentosrevision}}"
        sentinelone.data.origagentsiteid: "{{json_event.message.data.origagentsiteid}}"
        sentinelone.data.origagentuuid: "{{json_event.message.data.origagentuuid}}"
        sentinelone.data.origagentversion: "{{json_event.message.data.origagentversion}}"
        sentinelone.data.ruledescription: "{{json_event.message.data.ruledescription}}"
        sentinelone.data.rulescopeid: "{{json_event.message.data.rulescopeid}}"
        sentinelone.data.rulescopelevel: "{{json_event.message.data.rulescopelevel}}"
        sentinelone.data.severity: "{{json_event.message.data.severity}}"
        sentinelone.data.siteName: "{{json_event.message.data.siteName}}"
        sentinelone.data.sourcename: "{{json_event.message.data.sourcename}}"
        sentinelone.data.sourceparentprocesscommandline: "{{json_event.message.data.sourceparentprocesscommandline}}"
        sentinelone.data.sourceparentprocessintegritylevel: "{{json_event.message.data.sourceparentprocessintegritylevel}}"
        sentinelone.data.sourceparentprocesskey: "{{json_event.message.data.sourceparentprocesskey}}"
        sentinelone.data.sourceparentprocessmd5: "{{json_event.message.data.sourceparentprocessmd5}}"
        sentinelone.data.sourceparentprocessname: "{{json_event.message.data.sourceparentprocessname}}"
        sentinelone.data.sourceparentprocesspath: "{{json_event.message.data.sourceparentprocesspath}}"
        sentinelone.data.sourceparentprocesspid: "{{json_event.message.data.sourceparentprocesspid}}"
        sentinelone.data.sourceparentprocesssha1: "{{json_event.message.data.sourceparentprocesssha1}}"
        sentinelone.data.sourceparentprocesssha256: "{{json_event.message.data.sourceparentprocesssha256}}"
        sentinelone.data.sourceparentprocesssigneridentity: "{{json_event.message.data.sourceparentprocesssigneridentity}}"
        sentinelone.data.sourceparentprocessstarttime: "{{json_event.message.data.sourceparentprocessstarttime}}"
        sentinelone.data.sourceparentprocessstoryline: "{{json_event.message.data.sourceparentprocessstoryline}}"
        sentinelone.data.sourceparentprocesssubsystem: "{{json_event.message.data.sourceparentprocesssubsystem}}"
        sentinelone.data.sourceparentprocessusername: "{{json_event.message.data.sourceparentprocessusername}}"
        sentinelone.data.sourceprocesscommandline: "{{json_event.message.data.sourceprocesscommandline}}"
        sentinelone.data.sourceprocessfilepath: "{{json_event.message.data.sourceprocessfilepath}}"
        sentinelone.data.sourceprocessfilesingeridentity: "{{json_event.message.data.sourceprocessfilesingeridentity}}"
        sentinelone.data.sourceprocessintegritylevel: "{{json_event.message.data.sourceprocessintegritylevel}}"
        sentinelone.data.sourceprocesskey: "{{json_event.message.data.sourceprocesskey}}"
        sentinelone.data.sourceprocessmd5: "{{json_event.message.data.sourceprocessmd5}}"
        sentinelone.data.sourceprocessname: "{{json_event.message.data.sourceprocessname}}"
        sentinelone.data.sourceprocesspid: "{{json_event.message.data.sourceprocesspid}}"
        sentinelone.data.sourceprocesssha1: "{{json_event.message.data.sourceprocesssha1}}"
        sentinelone.data.sourceprocesssha256: "{{json_event.message.data.sourceprocesssha256}}"
        sentinelone.data.sourceprocessstarttime: "{{json_event.message.data.sourceprocessstarttime}}"
        sentinelone.data.sourceprocessstoryline: "{{json_event.message.data.sourceprocessstoryline}}"
        sentinelone.data.sourceprocesssubsystem: "{{json_event.message.data.sourceprocesssubsystem}}"
        sentinelone.data.sourceprocessusername: "{{json_event.message.data.sourceprocessusername}}"
        sentinelone.data.systemUser: "{{json_event.message.data.systemUser}}"


  read_agent_realtime_info:
    actions:
      - set:
          host.os.version: "{{json_event.message.agentRealtimeInfo.agentOsName}}"
          host.os.family: "{{json_event.message.agentRealtimeInfo.agentOsType}}"
          organization.id: "{{json_event.message.agentRealtimeInfo.accountId}}"
          organization.name: "{{json_event.message.agentRealtimeInfo.accountName}}"

  read_agent_detection_info:
    actions:
      - set:
          host.domain: "{{json_event.message.agentDetectionInfo.agentDomain}}"

          sentinelone.agentDetectionInfo.agentLastLoggedInUserName: "{{json_event.message.agentDetectionInfo.agentLastLoggedInUserName}}"
          sentinelone.agentDetectionInfo.mitigationStatus: "{{json_event.message.agentDetectionInfo.agentLastLoggedInUserName}}"
          sentinelone.sitename: "{{json_event.message.agentDetectionInfo.siteName}}"
          sentinelone.groupname: "{{json_event.message.agentDetectionInfo.groupName}}"
          host.ip:
            - "{{json_event.message.agentDetectionInfo.agentIpV4}}"
            - "{{json_event.message.agentDetectionInfo.agentIpV6}}"
            - "{{json_event.message.agentDetectionInfo.externalIp}}"

  read_threat_info:
    actions:
    - set:
        sentinelone.data.accountName: "{{json_event.message.data.accountName}}"
        sentinelone.threatInfo.analystVerdict: "{{json_event.message.threatInfo.analystVerdict}}"
        sentinelone.threatInfo.analystVerdictDescription: "{{json_event.message.threatInfo.analystVerdictDescription}}"
        sentinelone.threatInfo.AuthenticationPackageName: "{{json_event.message.threatInfo.AuthenticationPackageName}}"
        sentinelone.threatInfo.automaticallyResolved: "{{json_event.message.threatInfo.automaticallyResolved}}"
        sentinelone.threatInfo.browserType: "{{json_event.message.threatInfo.browserType}}"
        sentinelone.threatInfo.certificateId: "{{json_event.message.threatInfo.certificateId}}"
        sentinelone.threatInfo.classification: "{{json_event.message.threatInfo.classification}}"
        sentinelone.threatInfo.classificationSource: "{{json_event.message.threatInfo.classificationSource}}"
        sentinelone.threatInfo.cloudFilesHashVerdict: "{{json_event.message.threatInfo.cloudFilesHashVerdict}}"
        sentinelone.threatInfo.confidenceLevel: "{{json_event.message.threatInfo.confidenceLevel}}"
        sentinelone.threatInfo.createdAt: "{{json_event.message.threatInfo.createdAt}}"
        sentinelone.threatInfo.detectionType: "{{json_event.message.threatInfo.detectionType}}"
        sentinelone.threatInfo.failedActions: "{{json_event.message.threatInfo.failedActions}}"
        sentinelone.threatInfo.fileSize: "{{json_event.message.threatInfo.fileSize}}"
        sentinelone.threatInfo.fileVerificationType: "{{json_event.message.threatInfo.fileVerificationType}}"
        sentinelone.threatInfo.identifiedAt: "{{json_event.message.threatInfo.identifiedAt}}"
        sentinelone.threatInfo.incidentStatus: "{{json_event.message.threatInfo.incidentStatus}}"
        sentinelone.threatInfo.incidentStatusDescription: "{{json_event.message.threatInfo.incidentStatusDescription}}"
        sentinelone.threatInfo.initiatedBy: "{{json_event.message.threatInfo.initiatedBy}}"
        sentinelone.threatInfo.initiatedByDescription: "{{json_event.message.threatInfo.initiatedByDescription}}"
        sentinelone.threatInfo.initiatingUserId: "{{json_event.message.threatInfo.initiatingUserId}}"
        sentinelone.threatInfo.initiatingUsername: "{{json_event.message.threatInfo.initiatingUsername}}"
        sentinelone.threatInfo.NewTargetUserName: "{{json_event.message.threatInfo.NewTargetUserName}}"
        sentinelone.threatInfo.isFileless: "{{json_event.message.threatInfo.isFileless}}"
        sentinelone.threatInfo.isValidCertificate: "{{json_event.message.threatInfo.isValidCertificate}}"
        sentinelone.threatInfo.maliciousProcessArguments: "{{json_event.message.threatInfo.maliciousProcessArguments}}"
        sentinelone.threatInfo.md5: "{{json_event.message.threatInfo.md5}}"
        sentinelone.threatInfo.mitigationStatusDescription: "{{json_event.message.threatInfo.mitigationStatusDescription}}"
        sentinelone.threatInfo.originatorProcess: "{{json_event.message.threatInfo.originatorProcess}}"
        sentinelone.threatInfo.pendingActions: "{{json_event.message.threatInfo.pendingActions}}"
        sentinelone.threatInfo.processUser: "{{json_event.message.threatInfo.processUser}}"
        sentinelone.threatInfo.rebootRequired: "{{json_event.message.threatInfo.rebootRequired}}"
        sentinelone.threatInfo.threatId: "{{json_event.message.threatInfo.threatId}}"
        sentinelone.threatInfo.updatedAt: "{{json_event.message.threatInfo.updatedAt}}"
        file.extension: "{{json_event.message.threatInfo.fileExtension |lower}}"
        file.path: "{{json_event.message.threatInfo.filePath}}"
        file.size: "{{json_event.message.threatInfo.fileSize}}"