name: cloudflare-network-gateway
pipeline:
  - name: json_event
    external:
      name: json.parse-json
      properties:
        input_field: "{{original.message}}"
  - name: set_ecs_fields
  - name: set_cloudflare_fields
  
stages:
  set_ecs_fields:
    actions:
      - set:
          "@timestamp": '{{json_event.message.Datetime}}'
          destination.ip: '{{json_event.message.DestinationIP}}'
          destination.port: '{{json_event.message.DestinationPort}}'
          device.id: '{{json_event.message.DeviceID}}'
          event.category: ["network"]
          event.dataset: "network_gateway"
          event.kind: 'event'
          event.type: ["info"]
          network.transport: '{{json_event.message.Transport}}'
          user.email: '{{json_event.message.Email}}'
          user.id: '{{json_event.message.UserID}}'
          source.ip: '{{json_event.message.SourceIP}}'
          source.port: '{{json_event.message.Transport}}'
  set_cloudflare_fields:
    actions:
      - set:
          cloudflare: "{{% for key, value in json_event.message.items() %}{% if value not in ['NA', ''] %}'{{key}}': r'{{value}}',{% endif %}{% endfor %}}" #'{{json_event.message}}'