name: aether
pipeline:
  - name: json_event
    external:
      name: json.parse-json

  - name: ecs_categorization_fields
  - name: read_exploit_counters
  - name: malware_counters
  - name: program_blocked_counters
  - name: threats_by_av_counters
  - name: pups_counters

stages:
  ecs_categorization_fields:
    actions:
      - set:
          event.kind: "metric"
          event.category: [ "host" ]
          event.type: [ "info" ]

  read_exploit_counters:
    actions:
      - set:
          aether.exploit_counters.total_affected_devices: "{{json_event.message.exploit_counters.total_affected_devices}}"
          aether.exploit_counters.total_alerts: "{{json_event.message.exploit_counters.total_alerts}}"
          aether.exploit_counters.total_data_access: "{{json_event.message.exploit_counters.total_data_access}}"
          aether.exploit_counters.total_executed: "{{json_event.message.exploit_counters.total_executed}}"
          aether.exploit_counters.total_external_communications: "{{json_event.message.exploit_counters.total_external_communications}}"

  malware_counters:
    actions:
      - set:
          aether.malware_counters.total_affected_devices: "{{json_event.message.malware_counters.total_affected_devices}}"
          aether.malware_counters.total_alerts: "{{json_event.message.malware_counters.total_alerts}}"
          aether.malware_counters.total_data_access: "{{json_event.message.malware_counters.total_data_access}}"
          aether.malware_counters.total_executed: "{{json_event.message.malware_counters.total_executed}}"
          aether.malware_counters.total_external_communications: "{{json_event.message.malware_counters.total_external_communications}}"

  program_blocked_counters:
    actions:
      - set:
          aether.program_blocked_counters.total_programs_blocked: "{{json_event.message.program_blocked_counters.total_programs_blocked}}"

  threats_by_av_counters:
    actions:
      - set:
          aether.threats_by_av_counters.total_dangerous_actions_blocked_by_av: "{{json_event.message.threats_by_av_counters.total_dangerous_actions_blocked_by_av}}"
          aether.threats_by_av_counters.total_devices_blocked_by_av: "{{json_event.message.threats_by_av_counters.total_devices_blocked_by_av}}"
          aether.threats_by_av_counters.total_intrusion_attempted_blocked_by_av: "{{json_event.message.threats_by_av_counters.total_intrusion_attempted_blocked_by_av}}"
          aether.threats_by_av_counters.total_malware_urls_blocked_by_av: "{{json_event.message.threats_by_av_counters.total_malware_urls_blocked_by_av}}"
          aether.threats_by_av_counters.total_phishing_detected_by_av: "{{json_event.message.threats_by_av_counters.total_phishing_detected_by_av}}"
          aether.threats_by_av_counters.total_tracking_cookies_detected_by_av: "{{json_event.message.threats_by_av_counters.total_tracking_cookies_detected_by_av}}"

  pups_counters:
    actions:
      - set:
          aether.pups_counters.total_affected_devices: "{{json_event.message.pups_counters.total_affected_devices}}"
          aether.pups_counters.total_alerts: "{{json_event.message.pups_counters.total_alerts}}"
          aether.pups_counters.total_data_access: "{{json_event.message.pups_counters.total_data_access}}"
          aether.pups_counters.total_executed: "{{json_event.message.pups_counters.total_executed}}"
          aether.pups_counters.total_external_communications: "{{json_event.message.pups_counters.total_external_communications}}"