name: aether
pipeline:
  - name: json_event
    external:
      name: json.parse-json

  - name: ecs_categorization_fields
  - name: read_exploit_counters
  - name: malware_counters
  - name: program_blocked_counters
  - name: threats_by_av_counters
  - name: pups_counters
  - name: main_stage
  - name: translate_event_type
  - name: translate_action_for_attack
  - name: translate_action_for_detection
  - name: translate_protection_mode
  - name: translate_reclassified_to_type
  - name: translate_like_lihood_of_being_malicious
  - name: translate_discard_motive
  - name: translate_lock_plus_rule_id
  - name: translate_detected_by
  - name: translate_platform_id
  - name: translate_malware_category
  - name: translate_malware_type
  - name: translate_network_activity_type
  - name: translate_direction
  - name: translate_local_endpoint
  - name: translate_type
  - name: translate_rule_risk
  - name: translate_status
  - name: translate_device_type


stages:

  ecs_categorization_fields:
    actions:
      - set:
          event.kind: "event"
          event.category: [ "host" ]
          event.type: [ "info" ]

  main_stage:
    actions:
      - set:
          aether.accessed_data: "{{json_event.message.accessed_data}}"
          aether.action: "{{json_event.message.action}}"
          aether.alias: "{{json_event.message.alias}}"
          aether.count: "{{json_event.message.count}}"
          aether.custom_group_folder_id: "{{json_event.message.custom_group_folder_id}}"
          aether.custom_group_folder_info: "{{json_event.message.custom_group_folder_info}}"
          aether.date: "{{json_event.message.date}}"
          aether.description: "{{json_event.message.description}}"
          aether.detected_by: "{{json_event.message.detected_by}}"
          aether.detection_technology: "{{json_event.message.detection_technology}}"
          aether.device_id: "{{json_event.message.device_id}}"
          aether.device_type: "{{json_event.message.device_type}}"
          aether.direction: "{{json_event.message.direction}}"
          aether.discard_motive: "{{json_event.message.discard_motive}}"
          aether.domain: "{{json_event.message.domain}}"
          aether.dwell_time: "{{json_event.message.dwell_time}}"
          aether.endpoint_event_date: "{{json_event.message.endpoint_event_date}}"
          aether.event_id: "{{json_event.message.event_id}}"
          aether.event_type: "{{json_event.message.event_type}}"
          aether.excluded: "{{json_event.message.excluded}}"
          aether.exploit_technique: "{{json_event.message.exploit_technique}}"
          aether.file_info_discard: "{{json_event.message.file_info_discard}}"
          aether.filed_date: "{{json_event.message.filed_date}}"
          aether.hash: "{{json_event.message.hash}}"
          aether.host_name: "{{json_event.message.host_name}}"
          aether.id: "{{json_event.message.id}}"
          aether.instance_id: "{{json_event.message.instance_id}}"
          aether.ip_address: "{{json_event.message.ip_address}}"
          aether.is_excluded: "{{json_event.message.is_excluded}}"
          aether.item_name: "{{json_event.message.item_name}}"
          aether.like_lihood_of_being_malicious: "{{json_event.message.like_lihood_of_being_malicious}}"
          aether.lock_plus_rule_id: "{{json_event.message.lock_plus_rule_id}}"
          aether.made_external_connections: "{{json_event.message.made_external_connections}}"
          aether.malware_category: "{{json_event.message.malware_category}}"
          aether.malware_name: "{{json_event.message.malware_name}}"
          aether.malware_type: "{{json_event.message.malware_type}}"
          aether.network_activity_type: "{{json_event.message.network_activity_type}}"
          aether.number_of_occurrences: "{{json_event.message.number_of_occurrences}}"
          aether.path: "{{json_event.message.path}}"
          aether.platform_id: "{{json_event.message.platform_id}}"
          aether.protection_mode: "{{json_event.message.protection_mode}}"
          aether.protocol: "{{json_event.message.protocol}}"
          aether.reclassified_to_type: "{{json_event.message.reclassified_to_type}}"
          aether.risk: "{{json_event.message.risk}}"
          aether.rule_configuration_id: "{{json_event.message.rule_configuration_id}}"
          aether.rule_id: "{{json_event.message.rule_id}}"
          aether.rule_mitre: "{{json_event.message.rule_mitre}}"
          aether.rule_name: "{{json_event.message.rule_name}}"
          aether.rule_obsolete: "{{json_event.message.rule_obsolete}}"
          aether.rule_risk: "{{json_event.message.rule_risk}}"
          aether.security_event_date: "{{json_event.message.security_event_date}}"
          aether.since_until_filed: "{{json_event.message.since_until_filed}}"
          aether.site_id: "{{json_event.message.site_id}}"
          aether.site_name: "{{json_event.message.site_name}}"
          aether.source_ip: "{{json_event.message.source_ip}}"
          aether.source_machine_name: "{{json_event.message.source_machine_name}}"
          aether.source_user: "{{json_event.message.source_user}}"
          aether.status: "{{json_event.message.status}}"
          aether.user_name: "{{json_event.message.user_name}}"
          aether.was_run: "{{json_event.message.was_run}}"

  read_exploit_counters:
    actions:
      - set:
          aether.exploit_counters.total_affected_devices: "{{json_event.message.exploit_counters.total_affected_devices}}"
          aether.exploit_counters.total_alerts: "{{json_event.message.exploit_counters.total_alerts}}"
          aether.exploit_counters.total_data_access: "{{json_event.message.exploit_counters.total_data_access}}"
          aether.exploit_counters.total_executed: "{{json_event.message.exploit_counters.total_executed}}"
          aether.exploit_counters.total_external_communications: "{{json_event.message.exploit_counters.total_external_communications}}"

  malware_counters:
    actions:
      - set:
          aether.malware_counters.total_affected_devices: "{{json_event.message.malware_counters.total_affected_devices}}"
          aether.malware_counters.total_alerts: "{{json_event.message.malware_counters.total_alerts}}"
          aether.malware_counters.total_data_access: "{{json_event.message.malware_counters.total_data_access}}"
          aether.malware_counters.total_executed: "{{json_event.message.malware_counters.total_executed}}"
          aether.malware_counters.total_external_communications: "{{json_event.message.malware_counters.total_external_communications}}"

  program_blocked_counters:
    actions:
      - set:
          aether.program_blocked_counters.total_programs_blocked: "{{json_event.message.program_blocked_counters.total_programs_blocked}}"

  threats_by_av_counters:
    actions:
      - set:
          aether.threats_by_av_counters.total_dangerous_actions_blocked_by_av: "{{json_event.message.threats_by_av_counters.total_dangerous_actions_blocked_by_av}}"
          aether.threats_by_av_counters.total_devices_blocked_by_av: "{{json_event.message.threats_by_av_counters.total_devices_blocked_by_av}}"
          aether.threats_by_av_counters.total_intrusion_attempted_blocked_by_av: "{{json_event.message.threats_by_av_counters.total_intrusion_attempted_blocked_by_av}}"
          aether.threats_by_av_counters.total_malware_urls_blocked_by_av: "{{json_event.message.threats_by_av_counters.total_malware_urls_blocked_by_av}}"
          aether.threats_by_av_counters.total_phishing_detected_by_av: "{{json_event.message.threats_by_av_counters.total_phishing_detected_by_av}}"
          aether.threats_by_av_counters.total_tracking_cookies_detected_by_av: "{{json_event.message.threats_by_av_counters.total_tracking_cookies_detected_by_av}}"

  pups_counters:
    actions:
      - set:
          aether.pups_counters.total_affected_devices: "{{json_event.message.pups_counters.total_affected_devices}}"
          aether.pups_counters.total_alerts: "{{json_event.message.pups_counters.total_alerts}}"
          aether.pups_counters.total_data_access: "{{json_event.message.pups_counters.total_data_access}}"
          aether.pups_counters.total_executed: "{{json_event.message.pups_counters.total_executed}}"
          aether.pups_counters.total_external_communications: "{{json_event.message.pups_counters.total_external_communications}}"

  translate_action_for_attack:
    # Indicates the action performed.
    actions:
      - translate:
        dictionary:
          # For indicators of attack, this can be one of these values:
          0: Undefined
          1: Informed
          2: Attack Blocked
        mapping:
          aether.action: aether.action_translated
        filter: '{{json_event.message.action != null }}'

  translate_action_for_detection:
    # Indicates the action performed.
    actions:
      - translate:
        dictionary:
          # For other detections, this can be one of these values:
          0: Allowed
          1: Moved Quarantine
          2: Blocked
          3: Killed
          4: Ignored
          5: Cleaned
          6: Deleted
          7: Restored
          8: Allowed By Whitelist
          9: Write Blocked
          10: User Pending
          11: Uninstalled
          13: After Process Blocked
          14: Immediately Blocked
          15: Allowed By User
          16: Detected Restart Pending
          17: Allowed By Administrator
          18: Allowed on GW Installer
          21: Suspend Process
          1009: Informed
          1010: Unquarantine
          1011: Rename
          1012: Block URL

        mapping:
          aether.action: aether.action_translated
        filter: '{{json_event.message.action != null }}'


  translate_event_type:
    actions:
      - translate:
        dictionary:
          0: Malware
          1: Exploit
          2: PUPS
          3: Blocked Item
          6: Lock Plus Advanced Security
          7: Lock Plus Application Control
          8: Application Control
        mapping:
          aether.event_type: aether.event_type_translated
        filter: '{{json_event.message.event_type != null }}'

  translate_protection_mode:
    actions:
      - translate:
        dictionary:
          0: Undefined
          1: Audit
          2: Hardening
          3: Lock
        mapping:
          aether.protection_mode: aether.protection_mode_translated
        filter: '{{json_event.message.protection_mode != null }}'

  translate_reclassified_to_type:
    # Indicates the type to which it has been reclassified.
    actions:
      - translate:
        dictionary:
          0: Blocked
          1: Malware
          3: Pup
          6: Goodware
          11: Removed From List
        mapping:
          aether.reclassified_to_type: aether.reclassified_to_type_translated
        filter: '{{json_event.message.reclassified_to_type != null }}'

  translate_like_lihood_of_being_malicious:
    # Indicates the action performed.
    actions:
      - translate:
        dictionary:
          0: Low
          1: Medium
          2: High
          3: Very High
        mapping:
          aether.like_lihood_of_being_malicious: aether.like_lihood_of_being_malicious_translated
        filter: '{{json_event.message.like_lihood_of_being_malicious != null }}'

  translate_discard_motive:
    # Reason for discarding the knowledge sample.
    actions:
      - translate:
        dictionary:
          0: Unknown
          1: Other Reason
          2: File Max Size
        mapping:
          aether.discard_motive: aether.discard_motive_translated
        filter: '{{json_event.message.discard_motive != null }}'

  translate_lock_plus_rule_id:
    # Reason for discarding the knowledge sample.
    actions:
      - translate:
        dictionary:
          1: Obfuscated Params Powershell
          2: User Executed Powershell
          4: Unknown Scripts
          5: Locally Built Programs
          6: Documents With Macros
          7: Windows Boot Registry
          101: Forbidden Md5
          102: Forbidden Program Name
        mapping:
          aether.lock_plus_rule_id: aether.lock_plus_rule_id_translated
        filter: '{{json_event.message.lock_plus_rule_id != null }}'

  translate_detected_by:
    # Protection or technology in antivirus detections.
    actions:
      - translate:
        dictionary:
          1: On Demand Scan
          2: File Resident
          3: Mail Resident
          4: Firewall
          5: Device Control
          6: Exchange Mailbox
          7: Exchange Transport
          8: Exchange Antispam
          9: Web Protection
          10: Exchange Content
          11: Minerva
          12: Web Access Control
          13: Anti-theft
          14: Anti-tampering
          15: Personal Information Tracking
          16: Isolation
          17: Data Search Control
          18: Patch Management
          19: Personal Information Inventory
          20: Application Control
          21: Encryption USB
          22: Authorized Software
        mapping:
          aether.detected_by: aether.detected_by_translated
        filter: '{{json_event.message.detected_by != null }}'

  translate_device_type:
    # Device type in antivirus and firewall detections.
    actions:
      - translate:
        dictionary:
          0: Undefined
          1: Workstation
          2: Laptop
          3: Server
          4: Mobile
        mapping:
          aether.device_type: aether.device_type_translated
        filter: '{{json_event.message.device_type != null }}'

  translate_platform_id:
    # Platform of the affected device.
    actions:
      - translate:
        dictionary:
          0: Undefined
          1: Windows
          2: Linux
          3: Mac
          4: Android
          5: iOS
        mapping:
          aether.platform_id: aether.platform_id_translated
        filter: '{{json_event.message.platform_id != null }}'

  translate_malware_category:
    # Malware category in antivirus detections.
    actions:
      - translate:
        dictionary:
          1: Virus
          2: Spyware
          3: HackingPpnd
          4: Phishing
          5: Suspicious
          6: Blocked Operations
          7: Tracking Cookies
          8: Malware URL
          9: Others
        mapping:
          aether.malware_category: aether.malware_category_translated
        filter: '{{json_event.message.malware_category != null }}'

  translate_malware_type:
    # Malware type in antivirus detections.
    actions:
      - translate:
        dictionary:
          21: Nereus Heuritic
          22: Beta Trace Heuritic
          23: Smart Clean Heuritic
          24: Cloud Heuritic
          25: 1N
          26: Behavioral
          31: Confirmed Goodware
          32: Not Confirmed Goodware
          33: Unwanted Goodware
          34: Ranked
          35: Digital Signature
          101: Virus
          102: Worm
          103: Trojan
          104: TrojanPwdeal
          105: Dialer
          106: Joke
          107: Security Risk
          108: Spyware
          109: Adware
          110: Worm Fake Worm
          111: Tracking Cookie
          112: Pup
          113: Hacking Tool
          114: Vulnerability
          115: Max Size
          116: Zip of Death
          117: Packer of Death
          118: Hoax
          119: Phis Fraud
          120: Rootkit
          121: Backdoor
          122: Virus Constructor
          123: Malicious URL
          201: Advertising
          202: Toolbar
          203: Net Tool
          204: Advert Popup
          219: Illegal
          223: Internet Tools
          227: Offensive
          236: Society Education
          241: Content Filter
        mapping:
          aether.malware_type: aether.malware_type_translated
        filter: '{{json_event.message.malware_type != null }}'

  translate_network_activity_type:
    # Network activity type in firewall detections.
    actions:
      - translate:
        dictionary:
          1: IcmpAttack
          2: UdpPortScan
          3: HeaderLengths
          4: UdpFlood
          5: TcpFlagsCheck
          6: SmartWins
          7: IpExplicitPath
          8: LandAttack
          9: SmartDns
          10: IcmpFilterEchoRequest
          11: OsDetection
          12: SmartDhcp
          13: SynFlood
          14: SmartArp
          15: TcpPortScan
        mapping:
          aether.network_activity_type: aether.network_activity_type_translated
        filter: '{{json_event.message.network_activity_type != null }}'

  translate_direction:
    # Direction of firewall blocked connections.
    actions:
      - translate:
        dictionary:
          1: Incoming
          2: Outgoing
          3: Incoming and Outgoing
          4: Internal
        mapping:
          aether.direction: aether.direction_translated
        filter: '{{json_event.message.direction != null }}'

  translate_local_endpoint:
    # Firewall blocked connections for a local endpoint, in JSON format: Mac Address, IP Address, Port, and IP Type. IP type can be one of these values:

    actions:
      - translate:
        dictionary:
          0: Unknown
          1: IpV4
          2: IpV6
        mapping:
          aether.local_endpoint: aether.local_endpoint_translated
        filter: '{{json_event.message.local_endpoint != null }}'

  translate_type:
    # Type of device for device control detections.
    actions:
      - translate:
        dictionary:
          0: Undefined
          1: Removable Storage
          2: Image Capture
          3: Optical Storage
          4: Bluetooth
          5: Modem
          6: Mobile
        mapping:
          aether.type: aether.type_translated
        filter: '{{json_event.message.type != null }}'

  translate_rule_risk:
    # Indicates the rule risk for indicators of attack detections.
    actions:
      - translate:
        dictionary:
          0: Undefined
          1: Critical
          2: High
          3: Medium
          4: Low
          1000: Unknown
        mapping:
          aether.rule_risk: aether.rule_risk_translated
        filter: '{{json_event.message.rule_risk != null }}'

  translate_status:
    # Indicates the status in indicators of attack detections..
    actions:
      - translate:
        dictionary:
          0: Undefined
          1: Pending
          2: Filed
        mapping:
          aether.status: aether.status_translated
        filter: '{{json_event.message.status != null }}'