name: gateway-http
pipeline:
  - name: json_event
    external:
      name: json.parse-json
      properties:
        input_field: "{{original.message}}"
  - name: set_ecs_fields
  - name: set_cloudflare_fields

stages:
  set_ecs_fields:
    actions:
      - set:
          "@timestamp": '{{json_event.message.Datetime}}'
  set_cloudflare_fields:
    actions:
      - set:
          cloudflare: '{{json_event.message}}'