name: Kubernetes Audit Log
pipeline:
  - name: input
    external:
      name: json.parse-json
      properties:
        input_field: '{{original.message}}'
        output_field: event
  - name: fields
stages:
  fields:
    actions:
      - name: set
        set:
          user.id: '{{input.event.user.uid}}'
          url.path: '{{input.event.requestURI}}'
          source.ip: '{{input.event.sourceIPs[0]}}'
          user.name: '{{input.event.user.username}}'
          event.code: '{{input.event.auditID}}'
          user.roles: '{{input.event.user.groups}}'
          event.start: '{{input.event.requestReceivedTimestamp}}'
          event.action: '{{input.event.verb}}'
          action.outcome: '{{input.event.annotations["authorization.k8s.io/decision"]}}'
          user_agent.original: '{{input.event.userAgent}}'
          http.response.status_code: '{{input.event.responseStatus.code}}'
          action.properties.KubernetesName: '{{input.event.objectRef.name}}'
          action.properties.KubernetesResource: '{{input.event.objectRef.resource}}'
          action.properties.KubernetesNamespace: '{{input.event.objectRef.namespace}}'
          action.properties.KubernetesSubresource: '{{input.event.objectRef.subresource}}'
          action.properties.KubernetesRBACDecision: '{{input.event.annotations["authorization.k8s.io/reason"]}}'
      - name: set
        set:
          action.properties.KubernetesName: '{{input.event.responseObject.metadata.name}}'
        filter: '{{input.event.objectRef.name == null}}'
