name: wallix-bastion
pipeline:
  - name: parsed_event
    external:
      name: kv.parse-kv
  - name: set_extracted_fields
  - name: set_ecs_fields

stages:
  set_ecs_fields:
    actions:
      - set:
          event.kind: 'event'

      - translate:
        dictionary:
          'sessionlog': 'authentication'
          'Backup/Restore': ' database'
        mapping:
          parsed_event.message.type: event.category

      - translate:
        dictionary:
          'authentify': 'authentication'
        mapping:
          parsed_event.message.action: event.category

      - translate:
        dictionary:
          'add': ['creation']
          'edit': ['change']
          'delete': ['deletion']
          'list': ['access']
        mapping:
          parsed_event.message.action: event.type


      - translate:
        dictionary:
          'failure': ['denied']
        mapping:
          parsed_event.message.status: event.type
        filter: '{{parsed_event.message.action == "authentify"}}'

      - set:
          event.type: end
        filter: '{{parsed_event.message.infos.startswith("\"Closed")}}'

  set_extracted_fields:
    actions:
      - set:
          wallix: '{{ parsed_event.message}}'
          event.action: '{{ parsed_event.message.type}}'
          user.name: '{{ parsed_event.message.user}}'
          source.ip: '{{ parsed_event.message.client_ip}}'
          event.reason: '{{ parsed_event.message.infos }}'
