name: sophos-xdr
pipeline:
  - external:
      name: json.parse-json
      properties:
        input_field: "{{original.message}}"
        output_field: message
    name: parse_json

  - name: set_ecs_fields
  - name: set_sophos_fields

stages:
  set_ecs_fields:
    actions:
      - set:
          "@timestamp": "{{parse_json.message.calendar_time}}"

          event.kind: "event"
          event.ingested: "{{parse_json.message.ingestion_timestamp}}"
          event.severity: "{{parse_json.message.ioc_severity}}"

          user.name: "{{parse_json.message.meta_username}}"

          file.path: "{{parse_json.message.path}}"

          source.ip: "{{parse_json.message.meta_public_ip}}"

          client.mac: "{{parse_json.message.meta_mac_address}}"
          client.geo.country_iso_code: "{{parse_json.message.meta_public_ip_country_code}}"
          client.geo.postal_code: "{{parse_json.message.meta_public_ip_postal}}"
          client.geo.city_name: "{{parse_json.message.meta_public_ip_city}}"
          client.geo.country_name: "{{parse_json.message.meta_public_ip_country}}"

          host.name: "{{parse_json.message.meta_hostname}}"
          host.id: "{{parse_json.message.host_identifier}}"
          host.os.name: "{{parse_json.message.meta_os_name}}"
          host.os.version: "{{parse_json.message.meta_os_version}}"

          vulnerability.reference: "{{parse_json.message.ioc_detection_references[2:-2]}}"
          vulnerability.description: "{{parse_json.message.ioc_detection_description}}"

  set_sophos_fields:
    actions:
      - set:
          sophos.xdr.cvss: "{{parse_json.message.ioc_detection_cvss}}"
          sophos.xdr.id: "{{parse_json.message.endpoint_id}}"
          sophos.xdr.detection_attack: "{{parse_json.message.ioc_detection_attack}}"
          sophos.xdr.query.source: "{{parse_json.message.query_source}}"
          sophos.xdr.query.action: "{{parse_json.message.osquery_action}}"
          sophos.xdr.query.pack_version: "{{parse_json.message.meta_query_pack_version}}"
          sophos.xdr.query.name: "{{parse_json.message.query_name}}"
          sophos.xdr.endpoint.type: "{{parse_json.message.meta_endpoint_type}}"
