name: fortigate
pipeline:
  - name: parsed_event
    external:
      name: cef.parse-cef
    filter: '{{original.message.startswith("CEF")}}'

  - name: parsed_event
    filter: "{{original.message.startswith('CEF') == False}}"

  - name: field_extraction

stages:
  field_extraction:
    actions:
      - set:
          action.name: "{{parsed_event.message.action}}"
          destination.ip: "{{parsed_event.message.dstip}}"
          destination.address: "{{parsed_event.message.dstip}}"
          source.ip: "{{parsed_event.message.remip or parsed_event.message.srcip}}"
          source.address: "{{parsed_event.message.remip or parsed_event.message.srcip}}"
          destination.mac: "{{parsed_event.message.dstmac}}"
          destination.port: "{{parsed_event.message.dstport}}"
          destination.domain: "{{parsed_event.message.hostname}}"
          log.level: "{{parsed_event.message.level}}"
          log.description: "{{parsed_event.message.logdesc}}"
          event.code: "{{parsed_event.message.logid}}"
          event.type: "{{parsed_event.message.desc}}"
          event.reason: "{{parsed_event.message.reason}}"
          event.message: "{{parsed_event.message.msg}}"
          network.protocol: "{{parsed_event.message.service}}"
          network.transport: "{{parsed_event.message.proto}}"
          destination.nat.ip: "{{parsed_event.message.tranip}}"
          dns.rrname: "{{parsed_event.message.qname}}"
          dns.rrtype: "{{parsed_event.message.qtype}}"
          http.request.method: "{{parsed_event.message.method}}"
          destination.bytes: "{{parsed_event.message.rcvdbyte}}"
          destination.packets: "{{parsed_event.message.rcvdpkt}}"
          source.bytes: "{{parsed_event.message.sentbyte}}"
          source.packets: "{{parsed_event.message.sentpkt}}"
          source.nat.ip: "{{parsed_event.message.tunnelip}}"
          source.mac: "{{parsed_event.message.srcmac}}"
          source.port: "{{parsed_event.message.srcport}}"
          url.original: "{{parsed_event.message.url}}"
          url.full: "{{parsed_event.message.url}}"
          event.category: "{{parsed_event.message.type}}"
          action.type: "{{parsed_event.message.subtype}}"
          action.outcome: "{{parsed_event.message.status}}"
          network.application: "{{parsed_event.message.app}}"
          rule.category: "{{parsed_event.message.appcat or parsed_event.message.catdesc}}"
          rule.ruleset: "{{parsed_event.message.applist or parsed_event.message.policytype}}"
          rule.apprisk: "{{parsed_event.message.apprisk}}"
          action.outcome_reason: "{{parsed_event.message.outcome_reason}}"
          tmp.icmp_type: "{{parsed_event.message.icmptype}}"
          tmp.icmp_code: "{{parsed_event.message.icmpcode}}"
          source.user.name: "{{parsed_event.message.user}}"
          observer.ingress.interface.name: "{{parsed_event.message.srcintf}}"
          observer.egress.interface.name: "{{parsed_event.message.dstintf}}"
          fortigate.event.severity: "{{parsed_event.message.severity}}"