name: rsa-securedid
pipeline:
  - - name: parsed_description
      external:
        name: grok.match
        properties:
          input_field: '{{original.message}}'
          pattern: '%{EVENT_MESSAGE} | %{PROCESS_MESSAGE}'
          custom_patterns:
            - EVENT_MESSAGE: %{GREEDYDATA:action}
            - PROCESS_MESSAGE: %{GREEDYDATA:rsaadmin_title}:%{GREEDYDATA:tty};%{GREEDYDATA:pwd};%{GREEDYDATA:user};%{GREEDYDATA:command}

  - name: parsed_event
    external:
      name: dsv.parse-dsv
      properties:
        input_field: original.message
        output_field: message
        columnnames:
          - TIME
          - OBSERVER_HOSTNAME
          - RSA_SECUREID_CLASS
          - LOG_LEVEL
          - OBSERVER_SERIAL_NUMBER
          - DESTINATION_IP
          - SOURCE_IP
          - RSA_SECUREID_ACTION_NAME
          - EVENT_CODE
          - RSA_SECUREID_EVENT_OUTCOME
          - EVENT_REASON
          - RSA_SECUREID_SESSION_ID
          - USER_ID
          - RSA_SECUREID_SOURCE_ID
          - RSA_SECUREID_DOMAIN_ID
          - USER_NAME
          - USER_FIRSTNAME
          - USER_LASTNAME
          - AGENT_ID
          - RSA_SECUREID_AGENT_DOMAIN_ID
          - RSA_SECUREID_AGENT_IP
          - AGENT_NAME
          - RSA_SECUREID_POLICY_METHOD_ID
          - RSA_SECUREID_POLICY_METHOD_NAME
          - RSA_SECUREID_POLICY_ID
          - RSA_SECUREID_POLICY_EXPRESSION
          - RSA_SECUREID_OBJECTS_TYPE
          - RSA_SECUREID_OBJECTS_ID
          - RSA_SECUREID_OBJECTS_NAME
          - RSA_SECUREID_OBJECTS_SOURCE_ID
          - RSA_SECUREID_OBJECTS_SECURITY_ID
          - ARG_1
          - ARG_2
          - ARG_3
          - ARG_4
          - ARG_5
          - ARG_6
          - ARG_7
          - ARG_8
          - ARG_9
          - ARG_10
        delimiter: ","

  - name: set_grok_fields
  - name: set_csv_fields

stages:
  set_csv_fields:
    actions:
      - set:
          observer.hostname: "{{parsed_event.message.OBSERVER_HOSTNAME}}"
          observer.serial_number: "{{parsed_event.message.OBSERVER_SERIAL_NUMBER}}"
          source.ip: "{{parsed_event.message.SOURCE_IP}}"
          destination.ip: "{{parsed_event.message.DESTINATION_IP}}"
          log.level: "{{parsed_event.message.LOG_LEVEL}}"
          event.code: "{{parsed_event.message.EVENT_CODE}}"
          event.reason: "{{parsed_event.message.EVENT_REASON}}"
          user.id: "{{parsed_event.message.USER_ID}}"
          user.name: "{{parsed_event.message.USER_NAME}}"
          user.firstname: "{{parsed_event.message.USER_FIRSTNAME}}"
          user.lastname: "{{parsed_event.message.USER_LASTNAME}}"
          agent.id: "{{parsed_event.message.AGENT_ID}}"
          agent.name: "{{parsed_event.message.AGENT_NAME}}"
          event.outcome: "{{parsed_event.message.RSA_SECUREID_EVENT_OUTCOME}}"
          rsa.secureid.class: "{{parsed_event.message.RSA_SECUREID_CLASS}}"
          rsa.secureid.action.name: "{{parsed_event.message.RSA_SECUREID_ACTION_NAME}}"
          rsa.secureid.session.id: "{{parsed_event.message.RSA_SECUREID_SESSION_ID}}"
          rsa.secureid.source.id: "{{parsed_event.message.RSA_SECUREID_SOURCE_ID}}"
          rsa.secureid.domain.id: "{{parsed_event.message.RSA_SECUREID_DOMAIN_ID}}"
          rsa.secureid.agent.ip: "{{parsed_event.message.RSA_SECUREID_AGENT_IP}}"
          rsa.secureid.agent.domain.id: "{{parsed_event.message.RSA_SECUREID_AGENT_DOMAIN_ID}}"
          rsa.secureid.policy.method.id: "{{parsed_event.message.RSA_SECUREID_POLICY_METHOD_ID}}"
          rsa.secureid.policy.method.name: "{{parsed_event.message.RSA_SECUREID_POLICY_METHOD_NAME}}"
          rsa.secureid.policy.id: "{{parsed_event.message.RSA_SECUREID_POLICY_ID}}"
          rsa.secureid.policy.expression: "{{parsed_event.message.RSA_SECUREID_POLICY_EXPRESSION}}"
          rsa.secureid.objects.type: "{{parsed_event.message.RSA_SECUREID_OBJECTS_TYPE}}"
          rsa.secureid.objects.id: "{{parsed_event.message.RSA_SECUREID_OBJECTS_SOURCE_ID}}"
          rsa.secureid.objects.source.id: "{{parsed_event.message.RSA_SECUREID_OBJECTS_SOURCE_ID}}"
          rsa.secureid.objects.security.id: "{{parsed_event.message.RSA_SECUREID_SECURITY_ID}}"
          rsa.secureid.objects.name: "{{parsed_event.message.RSA_SECUREID_OBJECTS_NAME}}"
          event.action: "{{parsed_description.message.action}}"
          process.title: "{{parsed_description.message.rsaadmin_title}}"
          process.tty: "{{parsed_description.message.tty}}"
          process.working_directory: "{{parsed_description.message.pwd}}"
          process.env_vars: "{{parsed_description.message.user}}"
          process.command_line: "{{parsed_description.message.command}}"









