name: cato_sase
pipeline:
  - name: json_event
    external:
      name: json.parse-json
      properties:
        input_field: "{{original.message}}"
        output_field: output

  - name: set_common_fields

stages:
  set_common_fields:
    actions:
      # Default fields with predefined values
      - set:
          event.kind: "event"
          event.action: "{{json_event.output.action}}"
          event.reason: "{{json_event.output.event_message}}"

          agent.version: "{{json_event.output.client_version}}"

          destination.geo.country_name: "{{json_event.output.dest_country}}"
          destination.ip: "{{json_event.output.dest_ip}}"
          destination.port: "{{json_event.output.dest_port}}"

          host.name: "{{json_event.output.device_name}}"
          host.os.type: "{{json_event.output.os_type}}"
          host.os.version: "{{json_event.output.os_version}}"

          file.hash.sha256: "{{json_event.output.file_hash}}"
          file.name: "{{json_event.output.file_name}}"
          file.size: "{{json_event.output.file_size}}"

          host.ip: "{{json_event.output.host_ip}}"
          host.mac: "{{json_event.output.host_mac}}"
          network.transport: "{{json_event.output.ip_protocol}}"
          network.direction: "{{json_event.output.traffic_direction}}"
          url.original: "{{json_event.output.url}}"

          user.name: "{{json_event.output.user_name}}"
          user.email: "{{json_event.output.vpn_user_email}}"

          rule.id: "{{json_event.output.rule}}"
          rule.name: "{{json_event.output.rule_name}}"

          source.geo.country_name: "{{json_event.output.src_country}}"
          source.ip: "{{json_event.output.src_ip}}"
          source.nat.ip: "{{json_event.output.src_isp_ip}}"
          source.port: "{{json_event.output.src_port}}"

          cato.ad_name: "{{json_event.output.ad_name}}"
          cato.application: "{{json_event.output.application}}"
          cato.authentication_type: "{{json_event.output.authentication_type}}"
          cato.categories: "{{json_event.output.categories}}"
          cato.client_class: "{{json_event.output.client_class}}"
          cato.configured_host_name: "{{json_event.output.configured_host_name}}"
          cato.custom_categories: >
            [
              {% for record in json_event.output.custom_categories.split(',') %}
                  {% if record != "" %}"{{record | trim}}",{% endif %}
              {% endfor %}
            ]
          cato.custom_category: "{{json_event.output.custom_category}}"
          cato.dest_site: "{{json_event.output.dest_site}}"
          cato.dest_site_name: "{{json_event.output.dest_site_name}}"
          cato.directory_host_name: "{{json_event.output.directory_host_name}}"
          cato.directory_ip: "{{json_event.output.directory_ip}}"
          cato.directory_sync_result: "{{json_event.output.directory_sync_result}}"
          cato.directory_sync_type: "{{json_event.output.directory_sync_type}}"
          cato.event_sub_type: "{{json_event.output.event_sub_type}}"
          cato.event_type: "{{json_event.output.event_type}}"
          cato.incident_id: "{{json_event.output.incident_id}}"
          cato.link_type: "{{json_event.output.link_type}}"
          cato.login_type: "{{json_event.output.login_type}}"
          cato.registration_code: "{{json_event.output.registration_code}}"
          cato.src_site: "{{json_event.output.src_site}}"
          cato.src_site_name: "{{json_event.output.src_site_name}}"
          cato.subnet_name: "{{json_event.output.subnet_name}}"
          cato.threat_name: "{{json_event.output.threat_name}}"
          cato.threat_reference: "{{json_event.output.threat_reference}}"
          cato.threat_type: "{{json_event.output.threat_type}}"
          cato.threat_verdict: "{{json_event.output.threat_verdict}}"
          cato.tunnel_protocol: "{{json_event.output.tunnel_protocol}}"
          cato.windows_domain_name: "{{json_event.output.windows_domain_name}}"
