name: vmware-vcenter
pipeline:
  - name: parsed_event
    external:
      name: grok.match
      properties:
        input_field: "{{original.message}}"
        output_field: message
        pattern: "%{SESSION}"

        custom_patterns:
          SESSION: "%{WORD:Event} \[%{INT:Id}\] \[1-1\] \[%{TIMESTAMP_ISO8601:Timestamp}\] \[%{DATA:event_code}\] \[%{WORD:log_level}\] \[(.*?)\] \[(.*?)\] \[%{INT:RepeatedId}\] \[%{GREEDYDATA:description}\]
"

stages:
