name: cisco-ise
pipeline:
  - name: pre_parsed_event
    external:
      name: grok.match
      properties:
        input_field: original.message
        output_field: pre_message
        # pattern: "%{LOGLEVEL:status}:%{DATA:reason}:%{GREEDYDATA:kv}"
        pattern: "%{DATA:status}:%{GREEDYDATA:reason_with_kv}"

  - name: grok_timestamp_in_status
    filter: "{{pre_parsed_event.pre_message.status[0].isdigit()}}"
    external:
      name: grok.match
      properties:
        input_field: "{{pre_parsed_event.pre_message.reason_with_kv}}"
        output_field: time_message
        pattern: "%{DATA:start_of_msg}: %{DATA:reason},%{GREEDYDATA:end_of_msg}"

  - name: parsed_event
    filter: '{{":" in pre_parsed_event.pre_message.reason_with_kv}}'
    external:
      name: grok.match
      properties:
        input_field: "{{pre_parsed_event.pre_message.reason_with_kv}}"
        output_field: message
        pattern: "%{DATA:reason}:%{GREEDYDATA:kv}"

  - name: grok_conf
    filter: '{{"Configuration" in parsed_event.message.reason and ":" in pre_parsed_event.pre_message.reason_with_kv}}'
    external:
      name: grok.match
      properties:
        input_field: "{{parsed_event.message.reason.strip()}}"
        output_field: conf_result
        pattern: "Configuration %{WORD:change}"

  - name: parsed_kv_sentence
    filter: '{{":" in pre_parsed_event.pre_message.reason_with_kv}}'
    external:
      name: kv.parse-kv
      properties:
        input_field: "{{parsed_event.message.kv.strip()}}"
        output_field: result
        value_sep: "="
        item_sep: ';\s'

  - name: grok_mac
    filter: '{{parsed_kv_sentence.result.get("NAS Identifier") != None and "Configuration" not in parsed_event.message.reason}}'
    external:
      name: grok.match
      properties:
        input_field: '{{parsed_kv_sentence.result.get("NAS Identifier")}}'
        output_field: adress_mac
        pattern: "%{MAC:adress}:%{GREEDYDATA:word}"

  - name: set_ecs_fields
  - name: set_configuration_fields
  - name: set_network_fields
  - name: set_miscellaneous_fields

stages:
  set_ecs_fields:
    actions:
      - set:
          event.kind: event
          observer.vendor: Cisco
          observer.product: "Cisco ISE"
          event.type: ["info"]

  set_configuration_fields:
    actions:
      - set:
          user.name: "{{parsed_kv_sentence.result.Admin}}"
        filter: "{{parsed_kv_sentence.result.get('Admin') != None and 'Configuration' in parsed_event.message.reason}}"
      - set:
          event.category: configuration
          event.type: ["change"]
        filter: '{{"Configuration" in parsed_event.message.reason }}'
      - set:
          cisco.ise.config_object.name: '{{parsed_kv_sentence.result.get("Object Name")}}'
        filter: '{{parsed_kv_sentence.result.get("Object Name") != None and "Configuration" in parsed_event.message.reason}}'
      - set:
          cisco.ise.config_object.type: '{{parsed_kv_sentence.result.get("Object Type")}}'
        filter: '{{parsed_kv_sentence.result.get("Object Type") != None and "Configuration" in parsed_event.message.reason}}'
      - set:
          cisco.ise.config_action: "{{grok_conf.conf_result.change}}"
        filter: '{{grok_conf.conf_result.get("change") != None and "Configuration" in parsed_event.message.reason}}'

  set_network_fields:
    actions:
      - set:
          event.category: network
        filter: '{{"Configuration" not in parsed_event.message.reason }}'
      - set:
          source.domain: '{{parsed_kv_sentence.result.get("Server")}}'
        filter: '{{parsed_kv_sentence.result.get("Server") != None and "Configuration" not in parsed_event.message.reason}}'
      - set:
          user.name: '{{parsed_kv_sentence.result.get("Device login username")}}'
        filter: '{{parsed_kv_sentence.result.get("Device login username") != None and "Configuration" not in parsed_event.message.reason}}'
      - set:
          user.name: '{{parsed_kv_sentence.result.get("Calling Station Id")}}'
        filter: '{{parsed_kv_sentence.result.get("Calling Station Id") != None and "Configuration" not in parsed_event.message.reason}}'
      - set:
          cisco.ise.network_calling_station.id: '{{parsed_kv_sentence.result.get("Error Message")}}'
        filter: '{{parsed_kv_sentence.result.get("Error Message") != None and "Configuration" not in parsed_event.message.reason}}'
      - set:
          event.reason: '{{parsed_kv_sentence.result.get("Error Message")}}'
        filter: '{{parsed_kv_sentence.result.get("Error Message") != None and "Configuration" not in parsed_event.message.reason}}'
      - set:
          event.reason: '{{parsed_kv_sentence.result.get("Failure Reason")}}'
        filter: '{{parsed_kv_sentence.result.get("Failure Reason") != None and "Configuration" not in parsed_event.message.reason}}'
      - set:
          source.domain: '{{parsed_kv_sentence.result.get("Device Name")}}'
        filter: '{{parsed_kv_sentence.result.get("Device Name") != None and "Configuration" not in parsed_event.message.reason}}'
      - set:
          source.mac: "{{grok_mac.adress_mac.adress}}"
        filter: '{{parsed_kv_sentence.result.get("NAS Identifier") != None and "Configuration" not in parsed_event.message.reason}}'
      - set:
          source.ip: '{{parsed_kv_sentence.result.get("NAS IP Address") or parsed_kv_sentence.result.get("NAD Address") or parsed_kv_sentence.result.get("Device Ip") or parsed_kv_sentence.result.get("Network device IP")}}'
        filter: '{{(parsed_kv_sentence.result.get("NAS IP Address") != None or parsed_kv_sentence.result.get("NAD Address") != None or parsed_kv_sentence.result.get("Device Ip") != None or parsed_kv_sentence.result.get("Network device IP") != None) and "Configuration" not in parsed_event.message.reason}}'

  set_miscellaneous_fields:
    actions:
      - set:
          event.reason: "{{pre_parsed_event.pre_message.reason_with_kv}}"
        filter: '{{":" not in pre_parsed_event.pre_message.reason_with_kv and "=" not in pre_parsed_event.pre_message.reason_with_kv}}'

      - set:
          event.reason: "{{parsed_event.message.kv}}"
        filter: '{{":" in parsed_event.message.kv and "=" not in parsed_event.message.kv}}'

      - set:
          event.reason: "{{grok_timestamp_in_status.time_message.reason}}"
        filter: "{{pre_parsed_event.pre_message.status[0].isdigit()}}"
