name: cloudflare-audit-logs
pipeline:
  - name: json_event
    external:
      name: json.parse-json
      properties:
        input_field: "{{original.message}}"
  - name: set_ecs_fields
  - name: set_cloudflare_fields

stages:
  set_ecs_fields:
    actions:
      - set:
          "@timestamp": '{{json_event.message.When}}'
          user.email: '{{json_event.message.ActorEmail}}'
          user.id: '{{json_event.message.ActorID}}'
          source.ip: '{{json_event.message.ActorIP}}'

  set_cloudflare_fields:
    actions:
      - set:
          cloudflare: "{ {% for key, value in json_event.message.items() %}{% if value not in ['NA', '', [], None] %}'{{key}}': r'{{value}}',{% endif %}{% endfor %} }"  #'{{json_event.message}}'
