name: panda-security-siemfeeder
pipeline:
  - name: parse_kv
    external:
      name: kv.parse-kv
      properties:
        input_field: '{{ original.message.split("|")[7:] }}'
        output_field: message
        value_sep: '='
        item_sep: \s

  - name: parse_kv2
    external:
      name: kv.parse-kv
      properties:
        input_field: '{{ original.message.split("|")[8] }}'
        output_field: message
        value_sep: '='
        item_sep: \s

  - name: set_ecs_fields
  - name: set_cef_fields

stages:
  set_ecs_fields:
    actions:
      - set:
          event.kind: "event"
          event.category: [ "host" ]
          event.type: [ "info" ]

  set_cef_fields:
    actions:
      - set:
          siemfeeder.client: '{{parse_kv.message.Client}}'
          siemfeeder.date: '{{parse_kv.message.Date}}'
          host.name: '{{parse_kv.message.MachineName}}'
          source.ip: '{{parse_kv.message.MachineIP}}'
          user.name: '{{parse_kv.message.User}}'
          host.id: '{{parse_kv.message.MUID}}'
          siemfeeder.op: '{{parse_kv.message.Op}}'
          siemfeeder.hash: '{{parse_kv.message.Hash}}'
          siemfeeder.drivetype: '{{parse_kv.message.DriveType}}'
          registry.path: '{{parse_kv2.message.Path}}'
          siemfeeder.validsig: '{{parse_kv.message.ValidSig}}'
          siemfeeder.company: '{{parse_kv.message.Company}}'
          siemfeeder.broken: '{{parse_kv.message.Broken}}'
          siemfeeder.imagetype: '{{parse_kv.message.ImageType}}'
          siemfeeder.exetype: '{{parse_kv.message.ExeType}}'
          siemfeeder.prevalence: '{{parse_kv.message.Prevalence}}'
          siemfeeder.prevlastday: '{{parse_kv.message.PrevLastDay}}'
          siemfeeder.cat: '{{parse_kv.message.Cat}}'
          siemfeeder.mwname: '{{parse_kv.message.MWName}}'
          siemfeeder.targetpath: '{{parse_kv2.message.TargetPath}}'
          registry.key: '{{parse_kv.message.RegKey}}'