name: panda-security-siemfeeder
pipeline:
  - name: parse_kv
    external:
      name: kv.parse-kv
      properties:
        input_field: '{{ original.message.split("|")[7:] }}'
        output_field: message
        value_sep: '='
        item_sep: \s

  - name: parse_kv2
    external:
      name: kv.parse-kv
      properties:
        input_field: '{{ original.message.split("|")[8] }}'
        output_field: message
        value_sep: '='
        item_sep: \s

  - name: set_ecs_fields
  - name: set_cef_fields

stages:
  set_ecs_fields:
    actions:
      - set:
          event.kind: "event"
          event.category: [ "host" ]
          event.type: [ "info" ]

  set_cef_fields:
    actions:
      - set:
          siemfeeder: '{{parse_kv.message}}'
          host.name: '{{parse_kv.message.MachineName}}'
          source.ip: '{{parse_kv.message.MachineIP}}'
          user.name: '{{parse_kv.message.User}}'
          host.id: '{{parse_kv.message.MUID}}'
          registry.path: '{{parse_kv2.message.Path}}'
          registry.key: '{{parse_kv.message.RegKey}}'