name: SEKOIAIO actitivy logs
pipeline:
  - name: json_event
    external:
      name: json.parse-json
      properties:
        input_field: '{{original.message}}'

  - name: parse-the-date
    external:
      name: date.parse
      properties:
        input_field: '{{json_event.message.timestamp}}'
  - name: set_common_fields
stages:
  set_common_fields:
    actions:
      - set:
          agent.name: "{{json_event.message.observer.name}}"
          client.user.id: "{{json_event.message.identity.user_uuid}}"
          sekoiaio.activity.client.id: "{{json_event.message.identity.profile_identity}}"
          sekoiaio.activity.client.type: "{{json_event.message.identity.profile_type}}"
          client.ip: "{{json_event.message.visit.ip}}"
          user_agent.original: "{{json_event.message.visit.user_agent}}"
          http.request.method: "{{json_event.message.action.method}}"
          url.original: "{{json_event.message.action.url}}"
          url.path: "{{json_event.message.action.path}}"
          agent.version: "{{json_event.message.observer.version}}"
          http.request.referrer: "{{json_event.message.visit.referrer}}"
