name: crowdstrike-telemetry
pipeline:
  - name: parsed_event
    external:
      name: json.parse-json
      properties:
        input_field: "{{original.message}}"
        output_field: message

  - name: event_date
    external:
      name: date.parse
      properties:
        input_field: "{{parsed_event.message.timestamp}}"
        output_field: datetime

  - name: process_start_time
    external:
      name: date.parse
      properties:
        input_field: "{{parsed_event.message.ProcessStartTime}}"
        output_field: datetime

  - name: process_end_time
    external:
      name: date.parse
      properties:
        input_field: "{{parsed_event.message.ProcessEndTime}}"
        output_field: datetime
    filter: "{{parsed_event.message.ProcessEndTime != None}}"

  - name: set_common_fields

stages:
  set_common_fields:
    actions:
      - set:
          "@timestamp": "{{event_date.datetime}}"
          "process.command_line": "{{parsed_event.message.CommandLine}}"
          "process.executable": "{{parsed_event.message.ImageFileName}}"
          "process.thread.id": "{{parsed_event.message.SourceThreadId | int}}"
          "file.hash.md5": "{{parsed_event.message.MD5HashData}}"
          "process.parent.executable": "{{parsed_event.message.ParentBaseFileName}}"
          "process.parent.pid": "{{parsed_event.message.ParentProcessId}}"
          "process.end": "{{process_end_time.datetime}}"
          "process.start": "{{process_start_time.datetime}}"
          "process.pid": "{{parsed_event.message.RawProcessId}}"
          "process.args": "{{parsed_event.message.EnvironmentVariablesString}}"
          "file.hash.sha1": "{{parsed_event.message.SHA1HashData}}"
          "file.hash.sha256": "{{parsed_event.message.SHA256HashData}}"
          "user.id": "{{parsed_event.message.UserSid}}"
          "agent.id": "{{parsed_event.message.aid}}"
          "source.nat.ip": "{{parsed_event.message.aip}}"
          "source.nat.port": "{{parsed_event.message.LocalPort}}"
          "destination.nat.ip": "{{parsed_event.message.RemoteAddressIP4}}"
          "destination.nat.port": "{{parsed_event.message.RemotePort | int}}"
          "file.path": "{{parsed_event.message.TargetFileName}}"
          "crowdstrike.customer_id": "{{parsed_event.message.cid}}"
