name: crowdstrike-telemetry
pipeline:
  - name: parsed_event
    external:
      name: json.parse-json
      properties:
        input_field: "{{original.message}}"
        output_field: message

  - name: event_date
    external:
      name: date.parse
      properties:
        input_field: "{{parsed_event.message.timestamp}}"
        output_field: datetime

  - name: process_start_time
    external:
      name: date.parse
      properties:
        input_field: "{{parsed_event.message.ProcessStartTime}}"
        output_field: datetime

  - name: process_end_time
    external:
      name: date.parse
      properties:
        input_field: "{{parsed_event.message.ProcessEndTime}}"
        output_field: datetime
    filter: "{{parsed_event.message.ProcessEndTime != None}}"

  - name: set_common_fields
  - name: set_dns_fields
  - name: set_registry_fields

stages:
  set_registry_fields:
    actions:
      - set:
          "registry.value": "{{parsed_event.message.RegValueName}}"

      - set:
          "registry.key": '{{"\\".join(parsed_event.message.RegObjectName.split("\\")[3:])}}'
          "registry.hive": '{{parsed_event.message.RegObjectName.split("\\")[2]}}'
        filter: '{{parsed_event.message.get("RegObjectName") != None and "\\" in parsed_event.message.get("RegObjectName")}}'

      - set:
          "registry.path": '{{"\\".join(parsed_event.message.RegObjectName.split("\\")[2:])}}\{{parsed_event.message.RegValueName}}'
        filter: '{{parsed_event.message.get("RegValueName") != None or parsed_event.message.get("RegObjectName") != None}}'

  set_dns_fields:
    actions:
      - set:
          "dns.question.name": "{{parsed_event.message.DomainName}}"
          "dns.question.type": "{{parsed_event.message.RequestType}}"

      - translate:
        dictionary:
          "1": "A"
          "28": "AAAA"
          "18": "AFSDB"
          "42": "APL"
          "257": "CAA"
          "60": "CDNSKEY"
          "59": "CDS"
          "37": "CERT"
          "5": "CNAME"
          "62": "CSYNC"
          "49": "DHCID"
          "32769": "DLV"
          "39": "DNAME"
          "48": "DNSKEY"
          "43": "DS"
          "108": "EUI48"
          "109": "EUI64"
          "13": "HINFO"
          "55": "HIP"
          "65": "HTTPS"
          "45": "IPSECKEY"
          "25": "KEY"
          "36": "KX"
          "29": "LOC"
          "15": "MX"
          "35": "NAPTR"
          "2": "NS"
          "47": "NSEC"
          "50": "NSEC3"
          "51": "NSEC3PARAM"
          "61": "OPENPGPKEY"
          "12": "PTR"
          "46": "RRSIG"
          "17": "RP"
          "24": "SIG"
          "53": "SMIMEA"
          "6": "SOA"
          "33": "SRV"
          "44": "SSHFP"
          "64": "SVCB"
          "32768": "TA"
          "249": "TKEY"
          "52": "TLSA"
          "250": "TSIG"
          "16": "TXT"
          "256": "URI"
          "63": "ZONEMD"
        mapping:
          dns.question.type: dns.question.type

      - set:
          dns.answers: >
            [
              {% for record in parsed_event.message.get("IP4Records").split(";") %}
                  {% if record != "" %}{"data": "{{record}}"},{% endif %}
              {% endfor %}

              {% for record in parsed_event.message.get("IP6Records").split(";") %}
                  {% if record != "" %}{"data": "{{record}}"},{% endif %}
              {% endfor %}
            ]
        filter: '{{parsed_event.message.get("IP4Records") != None or parsed_event.message.get("IP6Records") != None}}'

  set_common_fields:
    actions:
      - set:
          "@timestamp": "{{event_date.datetime}}"
          "event.action": "{{parsed_event.message.event_simpleName}}"

          "process.command_line": "{{parsed_event.message.CommandLine}}"
          "process.executable": "{{parsed_event.message.ImageFileName}}"
          "process.thread.id": "{{parsed_event.message.SourceThreadId | int}}"
          "process.parent.executable": "{{parsed_event.message.ParentBaseFileName}}"
          "process.parent.pid": "{{parsed_event.message.ParentProcessId}}"
          "process.end": "{{process_end_time.datetime}}"
          "process.start": "{{process_start_time.datetime}}"
          "process.pid": "{{parsed_event.message.RawProcessId}}"
          "process.args": "{{parsed_event.message.EnvironmentVariablesString}}"

          "user.id": "{{parsed_event.message.UserSid}}"
          "user.name": "{{parsed_event.message.UserName}}"
          "agent.id": "{{parsed_event.message.aid}}"

          "source.ip": "{{parsed_event.message.LocalAddressIP6}}"
          "source.nat.ip": "{{parsed_event.message.aip}}"
          "source.nat.port": "{{parsed_event.message.LocalPort}}"

          "destination.ip": "{{parsed_event.message.RemoteAddressIP6}}"
          "destination.nat.ip": "{{parsed_event.message.RemoteAddressIP4}}"
          "destination.nat.port": "{{parsed_event.message.RemotePort | int}}"

          "file.path": "{{parsed_event.message.TargetFileName}}"
          "file.hash.sha1": "{{parsed_event.message.SHA1HashData}}"
          "file.hash.sha256": "{{parsed_event.message.SHA256HashData}}"
          "file.hash.md5": "{{parsed_event.message.MD5HashData}}"

          "crowdstrike.customer_id": "{{parsed_event.message.cid}}"

          "url.domain": "{{parsed_event.message.DownloadServer}}"
          "url.path": "{{parsed_event.message.DownloadPath}}"
      - set:
          "user.target.id": "{{parsed_event.message.UserRid}}"
          "user.target.group.id": "{{parsed_event.message.GroupRid}}"
        filter: "{{parsed_event.message.event_simpleName == 'UserAccountAddedToGroup'}}"
