name: panda-security-siemfeeder
pipeline:
  - name: parse_kv
    external:
      name: kv.parse-kv
      properties:
        input_field: '{{ original.message.split("|")[7:] }}'
        output_field: message
        value_sep: '='
        item_sep: \s

  - name: parse_kv2
    external:
      name: kv.parse-kv
      properties:
        input_field: '{{ original.message.split("|")[8] }}'
        output_field: message
        value_sep: '='
        item_sep: \s

  - name: set_ecs_fields

stages:
  set_ecs_fields:
    actions:
      - set:
          client.id: '{{parse_kv.message.Client}}'
          siemfeeder.Date: '{{parse_kv.message.Date}}'
          host.name: '{{parse_kv.message.MachineName}}'
          source.ip: '{{parse_kv.message.MachineIP}}'
          user.name: '{{parse_kv.message.User}}'
          host.id: '{{parse_kv.message.MUID}}'
          siemfeeder.Op: '{{parse_kv.message.Op}}'
          siemfeeder.Hash: '{{parse_kv.message.Hash}}'
          siemfeeder.DriveType: '{{parse_kv.message.DriveType}}'
          registry.path: '{{parse_kv2.message.Path}}'
          siemfeeder.ValidSig: '{{parse_kv.message.ValidSig}}'
          siemfeeder.Company: '{{parse_kv.message.Company}}'
          siemfeeder.Broken: '{{parse_kv.message.Broken}}'
          siemfeeder.ImageType: '{{parse_kv.message.ImageType}}'
          siemfeeder.ExeType: '{{parse_kv.message.ExeType}}'
          siemfeeder.Prevalence: '{{parse_kv.message.Prevalence}}'
          siemfeeder.PrevLastDay: '{{parse_kv.message.PrevLastDay}}'
          siemfeeder.Cat: '{{parse_kv.message.Cat}}'
          siemfeeder.MWName: '{{parse_kv.message.MWName}}'
          siemfeeder.TargetPath: '{{parse_kv2.message.TargetPath}}'
          registry.key: '{{parse_kv.message.RegKey}}'