name: citrix-adc
pipeline:
  - name: parsed_event
    external:
      name: cef.parse-cef

  - name: set_cef_header_fields

stages:
  set_cef_header_fields:
    actions:
      - set:
          event.kind: "event"
      - set:
          observer.vendor: "{{parsed_event.message.DeviceVendor}}"
          observer.product: "{{parsed_event.message.DeviceProduct}}"
          observer.version: "{{parsed_event.message.DeviceVersion}}"
      - set:
          source.ip: "{{parsed_event.message.src}}"
          source.port: "{{parsed_event.message.spt}}"
      - set:
          event.reason: "{{parsed_event.message.msg}}"
          event.action: "{{parsed_event.message.act}}"
          event.category: ["network"]
      - set:
          url.original: "{{parsed_event.message.request}}"
      - set:
          rule.name: "{{parsed_event.message.cs1}}"
          citrix.adc.alert.severity: "{{parsed_event.message.cs4}}"
      - translate:
        dictionary:
          "not blocked": ["allowed"]
          "blocked": ["denied"]
        mapping:
          event.action: event.type
