name: Microsoft Windows
pipeline:
  - name: json
    external:
      name: json.parse-json
      properties:
        input_field: "{{original.message}}"
        output_field: event
  - name: fields
  - name: set_action_properties
stages:
  set_action_properties:
    actions:
      - name: set
        set:
          action.properties.TargetDomainName: "{{ json.event.TargetDomainName }}"
          action.properties.TargetSid: "{{ json.event.TargetSid }}"
          action.properties.TargetUserName: "{{ json.event.TargetUserName }}"
          action.properties.TargetUserSid: "{{ json.event.TargetUserSid }}"
          action.properties.SubjectUserSid: "{{ json.event.SubjectUserSid }}"
          action.properties.SubjectUserName: "{{ json.event.SubjectUserName }}"
          action.properties.SubjectDomainName: "{{ json.event.SubjectDomainName }}"
          action.properties.SubjectLogonId: "{{ json.event.SubjectLogonId }}"
          action.properties.ObjectServer: "{{ json.event.ObjectServer }}"
          action.properties.ObjectType: "{{ json.event.ObjectType }}"
          action.properties.ObjectName: "{{ json.event.ObjectName }}"
          action.properties.ObjectValueName: "{{ json.event.ObjectValueName }}"
          action.properties.HandleId: "{{ json.event.HandleId }}"
          action.properties.OperationType: "{{ json.event.OperationType }}"
          action.properties.AccessMask: "{{ json.event.AccessMask }}"
          action.properties.AccessList: "{{ json.event.AccessList }}"
          action.properties.AccessReason: "{{ json.event.AccessReason }}"
          action.properties.Properties: "{{ json.event.Properties }}"
          action.properties.IpAddress: "{{ json.event.IpAddress }}"
          action.properties.IpPort: "{{ json.event.IpPort }}"
          action.properties.ShareName: "{{ json.event.ShareName }}"
          action.properties.ShareLocalPath: "{{ json.event.ShareLocalPath }}"
          action.properties.RelativeTargetName: "{{ json.event.RelativeTargetName }}"
          action.properties.OpcodeValue: "{{ json.event.OpcodeValue }}"
          action.properties.Task: "{{ json.event.Task }}"
          action.properties.Severity: "{{ json.event.Severity }}"
          action.properties.ProviderGuid: "{{ json.event.ProviderGuid }}"
          action.properties.ScriptBlockText: "{{ json.event.ScriptBlockText }}"
          action.properties.TicketOptions: "{{ json.event.TicketOptions }}"
          action.properties.Status: "{{ json.event.Status }}"
          action.properties.TicketEncryptionType: "{{ json.event.TicketEncryptionType }}"
          action.properties.PreAuthType: "{{ json.event.PreAuthType }}"
          action.properties.ServiceAccount: "{{ json.event.ServiceAccount }}"
          action.properties.ServiceFileName: '{{ json.event.get("Service File Name") or json.event.ServiceFileName }}'
          action.properties.ServiceName: "{{ json.event.ServiceName }}"
          action.properties.ServiceType: "{{ json.event.ServiceType }}"
          action.properties.ServiceStartType: "{{ json.event.ServiceStartType }}"
          action.properties.StartType: "{{ json.event.StartType }}"
          action.properties.ImagePath: "{{ json.event.ImagePath }}"
          action.properties.LogonType: "{{ json.event.LogonType }}"
          action.properties.LogonProcessName: "{{ json.event.LogonProcessName }}"
          action.properties.AuthenticationPackageName: "{{ json.event.AuthenticationPackageName }}"
          action.properties.ImageLoaded: "{{ json.event.ImageLoaded }}"
          action.properties.Signed: "{{ json.event.Signed }}"
          action.properties.Signature: "{{ json.event.Signature }}"
          action.properties.SignatureStatus: "{{ json.event.SignatureStatus }}"
          action.properties.SourceImage: "{{ json.event.SourceImage }}"
          action.properties.TargetImage: "{{ json.event.TargetImage }}"
          action.properties.GrantedAccess: "{{ json.event.GrantedAccess }}"
          action.properties.CallTrace: "{{ json.event.CallTrace | lower }}"
          action.properties.ThreatName: '{{ json.event.get("Threat Name") }}'
          action.properties.ExecutionName: '{{ json.event.get("Execution Name") }}'
          action.properties.Path: "{{ json.event.Path }}"
          action.properties.DetectionUser: '{{ json.event.get("Detection User") }}'
          action.properties.PrivilegeList: "{{ json.event.PrivilegeList }}"
          action.properties.WorkstationName: "{{ json.event.WorkstationName }}"
          action.properties.AttributeLDAPDisplayName: "{{ json.event.AttributeLDAPDisplayName }}"
          action.properties.AllowedToDelegateTo: "{{ json.event.AllowedToDelegateTo }}"
          action.properties.ObjectClass: "{{ json.event.ObjectClass }}"
          action.properties.Service: "{{ json.event.Service }}"
          action.properties.Keywords: "{{ json.event.Keywords }}"
          action.properties.ContextInfo: "{{ json.event.ContextInfo }}"
          action.properties.Payload: "{{ json.event.Payload }}"
          action.properties.SamAccountName: "{{ json.event.SamAccountName }}"
          action.properties.OldTargetUserName: "{{ json.event.OldTargetUserName }}"
          action.properties.NewTargetUserName: "{{ json.event.NewTargetUserName }}"
          action.properties.KeyLength: "{{ json.event.KeyLength }}"
          action.properties.ServicePrincipalNames: "{{ json.event.ServicePrincipalNames }}"
          action.properties.AttributeValue: "{{ json.event.AttributeValue }}"
          action.properties.HiveName: "{{ json.event.HiveName }}"
          action.properties.TaskName: "{{ json.event.TaskName }}"
          action.properties.TargetObject: "{{ json.event.TargetObject }}"
          action.properties.StartAddress: "{{ json.event.StartAddress }}"
          action.properties.PipeName: "{{ json.event.PipeName }}"
          action.properties.Device: "{{ json.event.Device }}"
          action.properties.Destination: "{{ json.event.Destination }}"
          action.properties.NewName: "{{ json.event.NewName }}"
          action.properties.BytesTotal: "{{ json.event.bytesTotal }}"
          action.properties.ProcessName: '{{ json.event.ProcessName or json.event.get("Process Name") }}'
          action.properties.AuditPolicyChanges: "{{ json.event.AuditPolicyChanges }}"
          action.properties.NewValue: '{{ json.event.NewValue or json.event.get("New Value") }}'
          action.properties.DeviceDescription: "{{ json.event.DeviceDescription }}"
          action.properties.ClassName: "{{ json.event.ClassName }}"
          action.properties.ClientAddress: "{{ json.event.ClientAddress }}"
          action.properties.AccountType: "{{ json.event.AccountType }}"
          action.properties.ApiCallerName: "{{ json.event.ApiCallerName }}"
          action.properties.DCName: "{{ json.event.DCName }}"
          action.properties.DeviceInstance: "{{ json.event.DeviceInstance }}"
          action.properties.DeviceName: "{{ json.event.DeviceName }}"
          action.properties.DomainPeer: "{{ json.event.DomainPeer }}"
          action.properties.DriverName: "{{ json.event.DriverName }}"
          action.properties.ErrorCode: '{{ json.event.get("Error Code") or json.event.ErrorCode }}'
          action.properties.EventType: "{{ json.event.EventType }}"
          action.properties.FailureName: "{{ json.event.FailureName }}"
          action.properties.HealthAttestationServer: '{{ json.event.get("Health Attestation Server") }}'
          action.properties.InstanceName: "{{ json.event.InstanceName }}"
          action.properties.IOCTL: "{{ json.event.IOCTL }}"
          action.properties.PID: "{{ json.event.PID }}"
          action.properties.ProcessPath: "{{ json.event.ProcessPath }}"
          action.properties.ProcessPid: "{{ json.event.ProcessPid }}"
          action.properties.StatusInformation: '{{ json.event.get("Status Information") }}'
          action.properties.StopTime: "{{ json.event.StopTime }}"
          action.properties.TimeSource: "{{ json.event.TimeSource }}"
          action.properties.updateGuid: "{{ json.event.updateGuid }}"
          action.properties.VsmPolicy: "{{ json.event.VsmPolicy }}"
          action.properties.VolumeName: "{{ json.event.VolumeName }}"
          action.properties.VolumeGuid: "{{ json.event.VolumeGuid }}"
          action.properties.TargetProcessId: "{{ json.event.TargetProcessId }}"
          action.properties.SourceProcessId: "{{ json.event.SourceProcessId }}"
          action.properties.ScriptBlockId: "{{ json.event.ScriptBlockId }}"
          action.properties.RunspaceId: "{{ json.event.RunspaceId }}"
          action.properties.SubStatus: "{{ json.event.SubStatus }}"
          action.properties.TargetServerName: "{{ json.event.TargetServerName }}"
          action.properties.TargetInfo: "{{ json.event.TargetInfo }}"
          action.properties.DisplayName: "{{ json.event.DisplayName }}"
          action.properties.UserPrincipalName: "{{ json.event.UserPrincipalName }}"
          action.properties.ScriptPath: "{{ json.event.ScriptPath }}"
          action.properties.HomeDirectory: "{{ json.event.HomeDirectory }}"
          action.properties.MemberName: "{{ json.event.MemberName }}"
          action.properties.MemberSid: "{{ json.event.MemberSid }}"
          action.properties.ServiceSid: "{{ json.event.ServiceSid }}"
          action.properties.Workstation: "{{ json.event.Workstation }}"
          action.properties.KeyName: "{{ json.event.KeyName }}"
          action.properties.KeyType: "{{ json.event.KeyType }}"
          action.properties.KeyFilePath: "{{ json.event.KeyFilePath }}"
          action.properties.Operation: "{{ json.event.Operation }}"
          action.properties.ReturnCode: "{{ json.event.ReturnCode }}"
          action.properties.User: "{{ json.event.User }}"
          action.properties.AccountName: "{{ json.event.AccountName }}"
          action.properties.Domain: "{{ json.event.Domain }}"
          action.properties.ActionName: "{{ json.event.ActionName }}"
          action.properties.Application: "{{ json.event.Application }}"
          action.properties.SidHistory: "{{ json.event.SidHistory }}"
          action.properties.Adapter: "{{ json.event.Adapter }}"
          action.properties.AdapterName: "{{ json.event.AdapterName }}"
          action.properties.AdapterSuffixName: "{{ json.event.AdapterSuffixName }}"
          action.properties.Auth: "{{ json.event.Auth }}"
          action.properties.AuthenticationAlgorithm: "{{ json.event.AuthenticationAlgorithm }}"
          action.properties.bytesTransferred: "{{ json.event.bytesTransferred }}"
          action.properties.CallerProcessName: "{{ json.event.CallerProcessName }}"
          action.properties.cfgattr: "{{ json.event.cfgattr }}"
          action.properties.cfgpath: "{{ json.event.cfgpath }}"
          action.properties.Cipher: "{{ json.event.Cipher }}"
          action.properties.CipherAlgorithm: "{{ json.event.CipherAlgorithm }}"
          action.properties.desc: "{{ json.event.desc }}"
          action.properties.DeviceInstanceId: "{{ json.event.DeviceInstanceId }}"
          action.properties.devname: "{{ json.event.devname }}"
          action.properties.DnsServerList: "{{ json.event.DnsServerList }}"
          action.properties.ExtensibleModulePath: "{{ json.event.ExtensibleModulePath }}"
          action.properties.fid_bcdDevice: "{{ json.event.fid_bcdDevice }}"
          action.properties.fid_idProduct: "{{ json.event.fid_idProduct }}"
          action.properties.fid_idVendor: "{{ json.event.fid_idVendor }}"
          action.properties.fid_UsbDevice: "{{ json.event.fid_UsbDevice }}"
          action.properties.FileList: "{{ json.event.FileList }}"
          action.properties.Hash: "{{ json.event.Hash }}"
          action.properties.Id: "{{ json.event.Id }}"
          action.properties.InterfaceDescription: "{{ json.event.InterfaceDescription }}"
          action.properties.InterfaceGuid: "{{ json.event.InterfaceGuid }}"
          action.properties.Ipaddress: "{{ json.event.Ipaddress }}"
          action.properties.job: "{{ json.event.job }}"
          action.properties.jobTitle: "{{ json.event.jobTitle }}"
          action.properties.Library: "{{ json.event.Library }}"
          action.properties.LocalMac: "{{ json.event.LocalMac }}"
          action.properties.LocalMAC: "{{ json.event.LocalMAC }}"
          action.properties.LocalName: "{{ json.event.LocalName }}"
          action.properties.MinimumPasswordLength: "{{ json.event.MinimumPasswordLength }}"
          action.properties.MinimumPasswordLengthAudit: "{{ json.event.MinimumPasswordLengthAudit }}"
          action.properties.NAME: "{{ json.event.NAME }}"
          action.properties.param1: "{{ json.event.param1 }}"
          action.properties.param2: "{{ json.event.param2 }}"
          action.properties.param3: "{{ json.event.param3 }}"
          action.properties.param4: "{{ json.event.param4 }}"
          action.properties.param5: "{{ json.event.param5 }}"
          action.properties.param6: "{{ json.event.param6 }}"
          action.properties.param7: "{{ json.event.param7 }}"
          action.properties.param8: "{{ json.event.param8 }}"
          action.properties.param9: "{{ json.event.param9 }}"
          action.properties.ParentDeviceInstanceId: "{{ json.event.ParentDeviceInstanceId }}"
          action.properties.PHYType: "{{ json.event.PHYType }}"
          action.properties.PolicyName: "{{ json.event.PolicyName }}"
          action.properties.OldValue: '{{ json.event.get("Old Value") }}'
          action.properties.RelaxMinimumPasswordLengthLimits: "{{ json.event.RelaxMinimumPasswordLengthLimits }}"
          action.properties.ResetCount: "{{ json.event.ResetCount }}"
          action.properties.ResetReason: "{{ json.event.ResetReason }}"
          action.properties.SentUpdateServer: '{{ json.event.get("Sent UpdateServer") }}'
          action.properties.server: "{{ json.event.server }}"
          action.properties.Source: "{{ json.event.Source }}"
          action.properties.SSID: "{{ json.event.SSID }}"
          action.properties.TaskContentNew: "{{ json.event.TaskContentNew }}"
          action.properties.TaskContentNew_Command: "{{ json.event.TaskContentNew_Command }}"
          action.properties.TaskContentNew_Args: "{{ json.event.TaskContentNew_Args }}"
          action.properties.Type: "{{ json.event.Type }}"
          action.properties.ui: "{{ json.event.ui }}"
          action.properties.UserContext: "{{ json.event.UserContext }}"
          action.properties.UserName: "{{ json.event.UserName }}"
          action.properties.UserSid: "{{ json.event.UserSid }}"
          action.properties.Volume: "{{ json.event.Volume }}"
          action.properties.WritePhase: "{{ json.event.WritePhase }}"
          action.properties.Zone: "{{ json.event.Zone }}"
          action.properties.TargetOutboundUserName: "{{ json.event.TargetOutboundUserName }}"
          action.properties.TargetOutboundDomainName: "{{ json.event.TargetOutboundDomainName }}"
          action.properties.ProcessGuid: "{{ json.event.ProcessGuid }}"
          action.properties.ZoneId: "{{ json.event.ZoneId }}"
          action.properties.ReferrerUrl: "{{ json.event.ReferrerUrl }}"
          action.properties.HostUrl: "{{ json.event.HostUrl }}"
          action.properties.ComputerName: "{{ json.event.ComputerName }}"
          action.properties.ProxyServer: "{{ json.event.ProxyServer }}"
          action.properties.LastAVSecurityIntelligenceAge: '{{ json.event.get("Last AV security intelligence age") }}'
          action.properties.LastASSecurityIntelligenceAge: '{{ json.event.get("Last AS security intelligence") }}'
          action.properties.LastQuickScanAge: '{{ json.event.get("Last quick scan age") }}'
          action.properties.LastFullScanAge: '{{ json.event.get("Last full scan age") }}'

          action.properties: ["{{ final.action.properties }}"]

  fields:
    actions:
      - name: set
        set:
          os.family: "windows"
          os.platform: "windows"
          event.code: "{{json.event.EventID}}"
          event.message: "{{json.event.Message}}"
          source.ip: "{{json.event.SourceIp or json.event.SourceAddress}}"
          source.port: "{{json.event.SourcePort}}"
          source.domain: "{{json.event.SourceHostname}}"
          event.provider: "{{json.event.SourceName}}"
          destination.ip: "{{json.event.DestAddress or json.event.DestinationIp}}"
          destination.port: "{{json.event.DestPort or json.event.DestinationPort}}"
          destination.domain: "{{json.event.DestinationHostname}}"
          process.pid: "{{json.event.ProcessID}}"
          process.thread.id: "{{json.event.ThreadID}}"
          process.ppid: "{{json.event.ParentProcessId}}"
          process.executable: "{{json.event.Image}}"
          network.transport: "{{json.event.Protocol}}"
          action.type: "{{json.event.Channel}}"
          action.record_id: "{{json.event.RecordNumber}}"
          user.id: "{{windows.SubjectUserSid or json.event.UserID}}"
          log.hostname: "{{json.event.Hostname}}"
          #          tmp.p_command_line: "{{json.event.CommandLine}}"
          process.working_directory: "{{json.event.CurrentDirectory}}"
          process.parent.executable: "{{json.event.ParentImage or json.event.ParentProcessName}}"
          #          tmp.parent.p_command_line: "{{json.event.ParentCommandLine}}"
          #          tmp.TargetFilename: "{{json.event.TargetFilename}}"
          file.created: "{{json.event.CreationUtcTime}}"
          dns.question.name: "{{json.event.QueryName}}"
          dns.response_code: "{{json.event.QueryStatus}}"
          dns.answers: "{{json.event.QueryResults}}"
          #          tmp.registry.value: "{{json.event.Details}}"
          url.original: "{{json.event.url or json.event.RemoteName}}"
          #          tmp.file: "{{json.event.LocalName}}"
          file.owner: "{{json.event.jobOwner}}"
          #          tmp.ConfigurationFileHash: "{{json.event.ConfigurationFileHash}}"
          #          tmp.Configuration: "{{json.event.Configuration}}"
          event.reason: "{{json.event.Description}}"

          process.parent.name: "{{process.parent.executable | basename}}"
          process.name: "{{process.executable | basename}}"
          #          tmp.Details: "{{tmp.registry.value}}"
          #          tmp.file: "{{tmp.TargetFilename}}"
          log.level: "{{windows.Severity}}"
          user.name: "{{windows.SubjectUserName}}"
          user.domain: "{{windows.SubjectDomainName}}"
#          tmp.registry.key: "{{windows.TargetObject}}"
#          process.id: "process.pid"
