name: sns
pipeline:
  - name: kv
    external:
      name: kv.parse-kv
      properties:
        input_field: '{{original.message}}'
        output_field: result
        value_sep: '='
        item_sep: \s
  - name: stage2
    external: null
stages:
  stage2:
    actions:
      - set:
          '@timestamp': '{{ kv.result.time }}'
          event.duration: '{{ kv.result.duration }}'
          event.timezone: '{{ kv.result.tz }}'
        name: set
      - set:
          destination.ip: '{{ kv.result.dst }}'
          destination.port: '{{ kv.result.dstport }}'
          destination.geo.continent_name: '{{ kv.result.dstcontinent }}'
          destination.geo.country_iso_code: '{{ kv.result.dstcountry }}'
        name: set
      - set:
          source.ip: '{{ kv.result.src }}'
          source.port: '{{ kv.result.srcport }}'
          source.mac: '{{ kv.result.srcmac }}'
          source.geo.continent_name: '{{ kv.result.srccontinent }}'
          source.geo.country_iso_code: '{{ kv.result.srccountry }}'
        name: set
      - set:
          stormshield.fw: '{{ kv.result.fw }}'
          stormshield.filter.action: '{{ kv.result.action }}'
        name: set
      - set:
          network.protocol: '{{ kv.result.proto }}'
          network.transport: '{{ kv.result.ipproto }}'
          network.type: '{{ kv.result.ipv }}'
          network.bytes: '{{ kv.result.sent + kv.result.rcvd }}'
          observert.ingress.interface.alias
      - set:
          rule.id: '{{ kv.result.ruleid }}'
          rule.category: '{{ kv.result.slotlevel }}'
