name: google_kubernetes_engine
pipeline:
  - name: json_event
    external:
      name: json.parse-json
      properties:
        input_field: "{{original.message}}"
  - name: google_kubernetes_engine

  - name: parse_kv
    external:
      name: kv.parse-kv
      properties:
        input_field: '{{ json_event.message.jsonPayload.MESSAGE }}'
        value_sep: '='
        item_sep: \s
stages:
  google_kubernetes_engine:
    actions:
      - set:
          event.kind: "event"
          event.category: "process"
          event.type: ['change']

          '@timestamp': "{{json_event.message.timestamp}}"

          # This field does not work
          event.reason: "{{parse_kv.message.msg}}"

          google_kubernetes_engine.insertId: "{{json_event.message.insertId}}"
          google_kubernetes_engine.jsonPayload.MESSAGE: "{{json_event.message.jsonPayload.MESSAGE}}"
          log.syslog.priority: "{{json_event.message.jsonPayload.PRIORITY}}"
          log.syslog.facility.code: "{{json_event.message.jsonPayload.SYSLOG_FACILITY}}"
          # Should be replaced by log.syslog.msgid when available
          google_kubernetes_engine.jsonPayload.SYSLOG_IDENTIFIER: "{{json_event.message.jsonPayload.SYSLOG_IDENTIFIER}}"
          # Should be replaced by host.boot.id when available
          google_kubernetes_engine.jsonPayload._BOOT_ID: "{{json_event.message.jsonPayload._BOOT_ID}}"
          google_kubernetes_engine.jsonPayload._CAP_EFFECTIVE: "{{json_event.message.jsonPayload._CAP_EFFECTIVE}}"
          process.command_line: "{{json_event.message.jsonPayload._CMDLINE}}"
          google_kubernetes_engine.jsonPayload._COMM: "{{json_event.message.jsonPayload._COMM}}"
          process.executable: "{{json_event.message.jsonPayload._EXE}}"
          file.gid: "{{json_event.message.jsonPayload._GID}}"
          host.name: "{{json_event.message.jsonPayload._HOSTNAME}}"
          host.id: "{{json_event.message.jsonPayload._MACHINE_ID}}"
          process.pid: "{{json_event.message.jsonPayload._PID}}"
          google_kubernetes_engine.jsonPayload._STREAM_ID: "{{json_event.message.jsonPayload._STREAM_ID}}"
          google_kubernetes_engine.jsonPayload._SYSTEMD_CGROUP: "{{json_event.message.jsonPayload._SYSTEMD_CGROUP}}"
          google_kubernetes_engine.jsonPayload._SYSTEMD_INVOCATION_ID: "{{json_event.message.jsonPayload._SYSTEMD_INVOCATION_ID}}"
          google_kubernetes_engine.jsonPayload._SYSTEMD_SLICE: "{{json_event.message.jsonPayload._SYSTEMD_SLICE}}"
          google_kubernetes_engine.jsonPayload._SYSTEMD_UNIT: "{{json_event.message.jsonPayload._SYSTEMD_UNIT}}"
          google_kubernetes_engine.jsonPayload._TRANSPORT: "{{json_event.message.jsonPayload._TRANSPORT}}"
          google_kubernetes_engine.jsonPayload._UID: "{{json_event.message.jsonPayload._UID}}"
          google_kubernetes_engine.logName: "{{json_event.message.logName}}"
          google_kubernetes_engine.receiveTimestamp: "{{json_event.message.receiveTimestamp}}"
          orchestrator.cluster.name: "{{json_event.message.resource.labels.cluster_name}}"
          server.geo.name: "{{json_event.message.resource.labels.location}}"
          google_kubernetes_engine.resource.labels.node_name: "{{json_event.message.resource.labels.node_name}}"
          cloud.project.id: "{{json_event.message.resource.labels.project_id}}"
          orchestrator.resource.type: "{{json_event.message.resource.type}}"
