name: digital_shadows_searchlight
pipeline:
  - external:
        name: json.parse-json
        properties:
            input_field: '{{original.message}}'
            output_field: message
    name: json_event
  - name: field_extraction
stages:
  field_extraction:
    actions:
      - set:
          event.id: "{{json_event.message.id}}"
          event.kind: alert
          event.category: threat
          event.type: indicator
          event.outcome: success
          event.reason: "{{json_event.message.classification}}"
          digital_shadows_searchlight.risk_level: "{{json_event.message.get('risk-assessment').get('risk-level')}}"
          digital_shadows_searchlight.risk_factors: "{{json_event.message.get('risk-factors')}}"
          rule.name: "{{json_event.message.title}}"
          rule.description: "{{json_event.message.description}}"
          related.hosts: "{{json_event.message.assets}}"
          event.start: "{{json_event.message.raised}}"
          event.end: "{{json_event.message.updated}}"