name: Cloudflare
pipeline:
  - name: json_event
    external:
      name: json.parse-json
      properties:
        input_field: "{{original.message}}"
  - name: stage1

stages:
  stage1:
    actions:
      - set:
          source.ip: "{{json_event.message.ClientIP or json_event.message.clientIP}}"
          destination.domain: "{{json_event.message.ClientRequestHost}}"
          http.request.method: "{{json_event.message.ClientRequestMethod}}"
          url.path: "{{json_event.message.ClientRequestURI}}"
          http.response.bytes: "{{json_event.message.EdgeResponseBytes}}"
          http.response.status_code: "{{json_event.message.EdgeResponseStatus}}"
          cloudflare.EdgeEndTimestamp: "{{json_event.message.EdgeEndTimestamp}}"
          cloudflare.EdgeStartTimestamp: "{{json_event.message.EdgeStartTimestamp}}"
          cloudflare.RayID: "{{json_event.message.RayID}}"
          cloudflare.EdgeResponseBytes: "{{json_event.message.EdgeResponseBytes}}"
          cloudflare.EdgeResponseStatus: "{{json_event.message.EdgeResponseStatus}}"
          event.action: "{{json_event.message.action}}"
          cloudflare.clientASNDescription: "{{json_event.message.clientASNDescription}}"
          source.as.number: "{{json_event.message.clientAsn}}"
          source.geo.country_name: "{{json_event.message.clientCountryName}}"
          cloudflare.clientRequestHTTPHost: "{{json_event.message.clientRequestHTTPHost}}"
          http.request.method: "{{json_event.message.clientRequestHTTPMethodName}}"
          network.protocol: "{{json_event.message.clientRequestHTTPProtocol}}"
          url.path: "{{json_event.message.clientRequestPath}}"
          cloudflare.clientRequestQuery: "{{json_event.message.clientRequestQuery}}"
          '@timestamp': "{{json_event.message.datetime}}"
          cloudflare.matchIndex: "{{json_event.message.matchIndex}}"
          cloudflare.metadata: "{{json_event.message.metadata}}"
          cloudflare.rayName: "{{json_event.message.rayName}}"
          rule.id: "{{json_event.message.ruleId}}"
          rule.ruleset: "{{json_event.message.rulesetId}}"
          cloudflare.sampleInterval: "{{json_event.message.sampleInterval}}"
          cloudflare.source: "{{json_event.message.source}}"
          user_agent.original: "{{json_event.message.userAgent}}"
          cloudflare.CacheCacheStatus: "{{json_event.message.CacheCacheStatus}}"
          cloudflare.CacheResponseBytes: "{{json_event.message.CacheResponseBytes}}"
          cloudflare.CacheResponseStatus: "{{json_event.message.CacheResponseStatus}}"
          cloudflare.CacheTieredFill: "{{json_event.message.CacheTieredFill}}"
          source.as.number: "{{json_event.message.ClientASN}}"
          source.geo.country_name: "{{json_event.message.ClientCountry}}"
          cloudflare.ClientDeviceType: "{{json_event.message.ClientDeviceType}}"
          cloudflare.ClientIPClass: "{{json_event.message.ClientIPClass}}"
          http.request.bytes: "{{json_event.message.ClientRequestBytes}}"
          cloudflare.ClientRequestPath: "{{json_event.message.ClientRequestPath}}"
          network.protocol: "{{json_event.message.ClientRequestProtocol}}"
          http.request.referer: "{{json_event.message.ClientRequestReferer}}"
          user_agent.original: "{{json_event.message.ClientRequestUserAgent}}"
          tls.cipher: "{{json_event.message.ClientSSLCipher}}"
          cloudflare.ClientSSLProtocol: "{{json_event.message.ClientSSLProtocol}}"
          source.port: "{{json_event.message.ClientSrcPort}}"
          cloudflare.ClientXRequestedWith: "{{json_event.message.ClientXRequestedWith}}"
          cloudflare.Cookies: "{{json_event.message.Cookies}}"
          cloudflare.EdgeColoCode: "{{json_event.message.EdgeColoCode}}"
          cloudflare.EdgeColoID: "{{json_event.message.EdgeColoID}}"
          cloudflare.EdgePathingOp: "{{json_event.message.EdgePathingOp}}"
          cloudflare.EdgePathingSrc: "{{json_event.message.EdgePathingSrc}}"
          cloudflare.EdgePathingStatus: "{{json_event.message.EdgePathingStatus}}"
          cloudflare.EdgeRateLimitAction: "{{json_event.message.EdgeRateLimitAction}}"
          cloudflare.EdgeRateLimitID: "{{json_event.message.EdgeRateLimitID}}"
          cloudflare.EdgeRequestHost: "{{json_event.message.EdgeRequestHost}}"
          cloudflare.EdgeResponseCompressionRatio: "{{json_event.message.EdgeResponseCompressionRatio}}"
          cloudflare.EdgeResponseContentType: "{{json_event.message.EdgeResponseContentType}}"
          cloudflare.EdgeServerIP: "{{json_event.message.EdgeServerIP}}"
          cloudflare.FirewallMatchesActions: "{{json_event.message.FirewallMatchesActions}}"
          cloudflare.FirewallMatchesRuleIDs: "{{json_event.message.FirewallMatchesRuleIDs}}"
          cloudflare.FirewallMatchesSources: "{{json_event.message.FirewallMatchesSources}}"
          cloudflare.OriginIP: "{{json_event.message.OriginIP}}"
          cloudflare.OriginResponseBytes: "{{json_event.message.OriginResponseBytes}}"
          cloudflare.OriginResponseHTTPExpires: "{{json_event.message.OriginResponseHTTPExpires}}"
          cloudflare.OriginResponseHTTPLastModified: "{{json_event.message.OriginResponseHTTPLastModified}}"
          cloudflare.OriginResponseStatus: "{{json_event.message.OriginResponseStatus}}"
          cloudflare.OriginResponseTime: "{{json_event.message.OriginResponseTime}}"
          cloudflare.OriginSSLProtocol: "{{json_event.message.OriginSSLProtocol}}"
          cloudflare.ParentRayID: "{{json_event.message.ParentRayID}}"
          cloudflare.RequestHeaders: "{{json_event.message.RequestHeaders}}"
          cloudflare.ResponseHeaders: "{{json_event.message.ResponseHeaders}}"
          cloudflare.SecurityLevel: "{{json_event.message.SecurityLevel}}"
          cloudflare.WAFAction: "{{json_event.message.WAFAction}}"
          cloudflare.WAFFlags: "{{json_event.message.WAFFlags}}"
          cloudflare.WAFMatchedVar: "{{json_event.message.WAFMatchedVar}}"
          cloudflare.WAFProfile: "{{json_event.message.WAFProfile}}"
          cloudflare.WAFRuleID: "{{json_event.message.WAFRuleID}}"
          cloudflare.WAFRuleMessage: "{{json_event.message.WAFRuleMessage}}"
          cloudflare.WorkerCPUTime: "{{json_event.message.WorkerCPUTime}}"
          cloudflare.WorkerStatus: "{{json_event.message.WorkerStatus}}"
          cloudflare.WorkerSubrequest: "{{json_event.message.WorkerSubrequest}}"
          cloudflare.WorkerSubrequestCount: "{{json_event.message.WorkerSubrequestCount}}"
          cloudflare.ZoneID: "{{json_event.message.ZoneID}}"