name: deepvisibility
pipeline:
  - name: json_event
    external:
      name: json.parse-json
      properties:
        input_field: "{{original.message}}"
  - name: rename_meta_fields
  - name: field_extraction
    filter: "{{json_event.message.dns == null}}"

  - name: rename_dns_fields
    filter: "{{json_event.message.dns != null}}"

stages:
  rename_meta_fields:
      actions:
      - set:
          agent.seq_id: "{{json_event.message.meta.seqId}}"
          agent.uuid: "{{json_event.message.meta.uuid}}"
          agent.trace_id: "{{json_event.message.meta.traceId}}"
          agent.version: "{{json_event.message.meta.agentVersion}}"
          agent.os.family: "{{json_event.message.meta.osFamily}}"
          agent.os.name: "{{json_event.message.meta.osName}}"
          agent.os.revision: "{{json_event.message.meta.osRevision}}"
          agent.machine.name: "{{json_event.message.meta.computerName}}"
          agent.machine.type: "{{json_event.message.meta.machineType}}"
          agent.managment_url: "{{json_event.message.meta.mgmtUrl}}"
          event.created: "{{json_event.message.timestamp.millisecondsSinceEpoch}}"

  rename_dns_fields:
      actions:
          - set:
              dns.trueContext.key: "{{json_event.message.dns.trueContext.key.value}}"
              dns.source.node.key: "{{json_event.message.dns.source.node.key.value}}"
              process.executable.node.key: "{{json_event.message.dns.source.executable.node.key.value}}"
              process.executable.start: "{{json_event.message.dns.source.executable.creationTime.millisecondsSinceEpoch}}"
              process.executable.name: "{{json_event.message.dns.source.executable.path}}"
              process.executable.is_dir: "{{json_event.message.dns.source.executable.isDir}}"
              process.executable.size_bytes: "{{json_event.message.dns.source.executable.sizeBytes}}"
              process.executable.signature.signed.identity: "{{json_event.message.dns.source.executable.signature.signed.identity}}"
              process.working_directory: "{{json_event.message.dns.source.executable.fileLocation}}"
              process.command_line: "{{json_event.message.dns.source.commandLine}}"
              process.pid: "{{json_event.message.dns.source.fullPid.pid}}"
              process.start: "{{json_event.message.dns.source.fullPid.startTime.millisecondsSinceEpoch}}"
              source.user.name: "{{json_event.message.dns.source.user.name}}"
              source.user.sid: "{{json_event.message.dns.source.user.sid}}"
              source.interactive: "{{json_event.message.dns.source.interactive}}"
              process.parent.node.key: "{{json_event.message.dns.source.parent.node.key.value}}"
              source.excluded: "{{json_event.message.dns.source.excluded}}"
              source.name: "{{json_event.message.dns.source.name}}"
              source.root: "{{json_event.message.dns.source.root}}"
              os.family: "{{json_event.message.dns.source.subsystem}}"
              source.session_id: "{{json_event.message.dns.source.sessionId}}"
              source.integrity_level: "{{json_event.message.dns.source.integrityLevel}}"
              source.is_wow64: "{{json_event.message.dns.source.isWow64}}"
              source.is_redirected_command_processor: "{{json_event.message.dns.source.isRedirectedCommandProcessor}}"
              source.trueContext.key: "{{json_event.message.dns.source.trueContext.key.value}}"
              process.counters.moduleLoad: "{{json_event.message.dns.source.counters.moduleLoad}}"
              process.counters.fileCreation: "{{json_event.message.dns.source.counters.fileCreation}}"
              process.counters.fileDeletion: "{{json_event.message.dns.source.counters.fileDeletion}}"
              process.counters.fileModification: "{{json_event.message.dns.source.counters.fileModification}}"
              process.counters.netConnOut: "{{json_event.message.dns.source.counters.netConnOut}}"
              process.counters.dnsLookups: "{{json_event.message.dns.source.counters.dnsLookups}}"
              dns.question.name: "{{json_event.message.dns.query}}"
              dns.answers.results: "{{json_event.message.dns.results}}"

  field_extraction:
    actions:
      - set:
          agent.domain: "{{json_event.message.agentDomain}}"
          agent.group: "{{json_event.message.agentGroupId}}"
          agent.id: "{{json_event.message.agentId}}"
          agent.infected: "{{json_event.message.agentInfected}}"
          source.ip: "{{json_event.message.agentIp}}"
          agent.name: "{{json_event.message.agentName}}"
          os.family: "{{json_event.message.agentOs}}"
          agent.timestamp: "{{json_event.message.agentTimestamp}}"
          agent.uuid: "{{json_event.message.agentUuid}}"
          agent.version: "{{json_event.message.agentVersion}}"
          event.createdAt: "{{json_event.message.createdAt}}"
          dns.count: "{{json_event.message.dnsCount}}"
          agent.type: "{{json_event.message.endpointMachineType}}"
          user.domain: "{{json_event.message.endpointName}}"
          os.name: "{{json_event.message.endpointOs}}"
          action.name: "{{json_event.message.eventType}}"
          file.hash.md5: "{{json_event.message.fileMd5}}"
          file.hash.sha256: "{{json_event.message.fileSha256}}"
          event.id: "{{json_event.message.id}}"
          indicator.boot_config_update_count: "{{json_event.message.indicatorBootConfigurationUpdateCount}}"
          indicator.evasion_count: "{{json_event.message.indicatorEvasionCount}}"
          indicator.exploitation_count: "{{json_event.message.indicatorExploitationCount}}"
          indicator.general_count: "{{json_event.message.indicatorGeneralCount}}"
          indicator.info_stealer_count: "{{json_event.message.indicatorInfostealerCount}}"
          indicator.injection_count: "{{json_event.message.indicatorInjectionCount}}"
          indicator.persistence_count: "{{json_event.message.indicatorPersistenceCount}}"
          indicator.post_exploitation_count: "{{json_event.message.indicatorPostExploitationCount}}"
          indicator.ransomware_count: "{{json_event.message.indicatorRansomwareCount}}"
          indicator.reconnaissance_count: "{{json_event.message.indicatorReconnaissanceCount}}"
          action.name_meta: "{{json_event.message.metaEventName}}"
          action.object_type: "{{json_event.message.objectType}}"
          process.parent.pid: "{{json_event.message.parentPid}}"
          process.ppid: "{{json_event.message.parentPid}}"
          process.parent.name: "{{json_event.message.parentProcessName}}"
          process.parent.start: "{{json_event.message.parentProcessStartTime}}"
          process.parent.entity_id: "{{json_event.message.parentProcessUniqueKey}}"
          process.pid: "{{json_event.message.pid}}"
          process.command_line: "{{json_event.message.processCmd}}"
#          process.name: "{{json_event.message.processDisplayName}}"
          process.pgid: "{{json_event.message.processGroupId}}"
          process.executable: "{{json_event.message.processImagePath}}"
          process.working_directory: "{{json_event.message.processImagePath}}"
          process.hash.sha1: "{{json_event.message.processImageSha1Hash}}"
#          process.integrity_level: "{{json_event.message.processIntegrityLevel}}"
#          process.is_redirected_cmd_processor: "{{json_event.message.processIsRedirectedCommandProcessor}}"
#          process.is_wow64: "{{json_event.message.processIsWow64}}"
          process.name: "{{json_event.message.processName}}"
#          process.root: "{{json_event.message.processRoot}}"
#          process.session_id: "{{json_event.message.processSessionId}}"
          process.start: "{{json_event.message.processStartTime}}"
#          process.sub_system: "{{json_event.message. processSubSystem }}"
          process.entity_id: "{{json_event.message.processUniqueKey}}"
          publisher: "{{json_event.message.publisher}}"
#          registry.change_count: "{{json_event.message.registryChangeCount}}"
          registry.key: "{{json_event.message.registryKeyPath}}"
#          registry.old_value.value: "{{json_event.message.registryOldValue}}"
#          registry.old_value.full_size: "{{json_event.message.registryOldValueFullSize}}"
#          registry.old_value.is_complete: "{{json_event.message.registryOldValueIsComplete}}"
#          registry.old_value.type: "{{json_event.message.registryOldValueType}}"
          registry.path: "{{json_event.message.registryPath}}"
#          registry.uid: "{{json_event.message.registryUid}}"
#          registry.uuid: "{{json_event.message.registryUuid}}"
          registry.value: "{{json_event.message.registryValue}}"
          registry.data.type: "{{json_event.message.registryValueType}}"
          related_to_threat: "{{json_event.message.relatedToThreat}}"
#          code_signature.signed_invalid_reason: "{{json_event.message.signatureSignedInvalidReason}}"
          code_signature.status: "{{json_event.message.signedStatus}}"
          site.name: "{{json_event.message.siteName}}"

#          process.active_content.field : "{{json_event.message.srcProcActiveContentFileId}}"
#          process.active_content.hash : "{{json_event.message.srcProcActiveContentHash}}"
#          process.active_content.path : "{{json_event.message.srcProcActiveContentPath}}"
#          process.active_content.signed_status : "{{json_event.message.srcProcActiveContentSignedStatus}}"
#          process.active_content.type : "{{json_event.message.srcProcActiveContentType}}"
#          process.bin_is_executable : "{{json_event.message.srcProcBinaryisExecutable}}"
#
#          process.display_name : "{{json_event.message.srcProcDisplayName}}"
#          process.image.md5 : "{{json_event.message.srcProcImageMd5}}"
#          process.image.path : "{{json_event.message.srcProcImagePath}}"
#          process.image.sha1 : "{{json_event.message.srcProcImageSha1}}"
#          process.image.sha256 : "{{json_event.message.srcProcImageSha256}}"
#          process.integrity_level : "{{json_event.message.srcProcIntegrityLevel}}"
#          process.is_native_64bit : "{{json_event.message.srcProcIsNative64Bit}}"
#          process.is_redirect_cmd_processor : "{{json_event.message.srcProcIsRedirectCmdProcessor}}"
#          process.is_story_line_root : "{{json_event.message.srcProcIsStorylineRoot}}"
#
#          parent.process.hash.md5 : "{{json_event.message.srcProcParentImageMd5}}"
#          parent.process.executable : "{{json_event.message.srcProcParentImagePath}}"
#          parent.process.hash.sha1 : "{{json_event.message.srcProcParentImageSha1}}"
#          parent.process.hash.sha256 : "{{json_event.message.srcProcParentImageSha256}}"
#          parent.process.name : "{{json_event.message.srcProcParentName}}"
          user.name: "{{json_event.message.user}}"
