name: deepvisibility
pipeline:
  - name: field_extraction

stages:
  field_extraction:
    actions:
      - set:
          agent.domain: "{{agentDomain}}"
          agent.group: "{{agentGroupId}}"
          agent.id: "{{agentId}}"
          agent.infected: "{{agentInfected}}"
          source.ip: "{{agentIp}}"
          agent.name: "{{agentName}}"
          os.family: "{{agentOs}}"
          agent.timestamp: "{{agentTimestamp}}"
          agent.uuid: "{{agentUuid}}"
          agent.version: "{{agentVersion}}"
          event.createdAt: "{{createdAt}}"
          dns.count: "{{dnsCount}}"
          agent.type: "{{endpointMachineType}}"
          user.name: "{{endpointName}}"
          os.name: "{{endpointOs}}"
          action.name: "{{eventType}}"
          file.hash.md5: "{{fileMd5}}"
          file.hash.sh256: "{{fileSha256}}"
          event.id: "{{id}}"
          indicator.boot_config_update_count: "{{indicatorBootConfigurationUpdateCount}}"
          indicator.evasion_count: "{{indicatorEvasionCount}}"
          indicator.exploitation_count: "{{indicatorExploitationCount}}"
          indicator.general_count: "{{indicatorGeneralCount}}"
          indicator.info_stealer_count: "{{indicatorInfostealerCount}}"
          indicator.injection_count: "{{indicatorInjectionCount}}"
          indicator.persistence_count: "{{indicatorPersistenceCount}}"
          indicator.post_exploitation_count: "{{indicatorPostExploitationCount}}"
          indicator.ransomware_count: "{{indicatorRansomwareCount}}"
          indicator.reconnaissance_count: "{{indicatorReconnaissanceCount}}"
          action.name_meta: "{{metaEventName}}"
          action.object_type: "{{objectType}}"
          process.parent.pid: "{{parentPid}}"
          process.ppid: "{{parentPid}}"
          process.parent.name: "{{parentProcessName}}"
          process.parent.start: "{{parentProcessStartTime}}"
          process.parent.entity_id: "{{parentProcessUniqueKey}}"
          process.pid: "{{pid}}"
          process.command_line: "{{processCmd}}"
#          process.name: "{{processDisplayName}}"
          process.pgid: "{{processGroupId}}"
          process.executable: "{{processImagePath}}"
          process.working_directory: "{{processImagePath}}"
          process.hash.sha1: "{{processImageSha1Hash}}"
#          process.integrity_level: "{{processIntegrityLevel}}"
#          process.is_redirected_cmd_processor: "{{processIsRedirectedCommandProcessor}}"
#          process.is_wow64: "{{processIsWow64}}"
          process.name: "{{processName}}"
#          process.root: "{{processRoot}}"
#          process.session_id: "{{processSessionId}}"
          process.start: "{{processStartTime}}"
#          process.sub_system: "{{ processSubSystem }}"
          process.entity_id: "{{processUniqueKey}}"
          publisher: "{{publisher}}"
#          registry.change_count: "{{registryChangeCount}}"
          registry.key: "{{registryKeyPath}}"
#          registry.old_value.value: "{{registryOldValue}}"
#          registry.old_value.full_size: "{{registryOldValueFullSize}}"
#          registry.old_value.is_complete: "{{registryOldValueIsComplete}}"
#          registry.old_value.type: "{{registryOldValueType}}"
          registry.path: "{{registryPath}}"
#          registry.uid: "{{registryUid}}"
#          registry.uuid: "{{registryUuid}}"
          registry.value: "{{registryValue}}"
          registry.data.type: "{{registryValueType}}"
          related_to_threat: "{{relatedToThreat}}"
#          code_signature.signed_invalid_reason: "{{signatureSignedInvalidReason}}"
          code_signature.status: "{{signedStatus}}"
          site.name: "{{siteName}}"

#          process.active_content.field : "{{srcProcActiveContentFileId}}"
#          process.active_content.hash : "{{srcProcActiveContentHash}}"
#          process.active_content.path : "{{srcProcActiveContentPath}}"
#          process.active_content.signed_status : "{{srcProcActiveContentSignedStatus}}"
#          process.active_content.type : "{{srcProcActiveContentType}}"
#          process.bin_is_executable : "{{srcProcBinaryisExecutable}}"
#
#          process.display_name : "{{srcProcDisplayName}}"
#          process.image.md5 : "{{srcProcImageMd5}}"
#          process.image.path : "{{srcProcImagePath}}"
#          process.image.sha1 : "{{srcProcImageSha1}}"
#          process.image.sha256 : "{{srcProcImageSha256}}"
#          process.integrity_level : "{{srcProcIntegrityLevel}}"
#          process.is_native_64bit : "{{srcProcIsNative64Bit}}"
#          process.is_redirect_cmd_processor : "{{srcProcIsRedirectCmdProcessor}}"
#          process.is_story_line_root : "{{srcProcIsStorylineRoot}}"
#
#          parent.process.hash.md5 : "{{srcProcParentImageMd5}}"
#          parent.process.executable : "{{srcProcParentImagePath}}"
#          parent.process.hash.sha1 : "{{srcProcParentImageSha1}}"
#          parent.process.hash.sha256 : "{{srcProcParentImageSha256}}"
#          parent.process.name : "{{srcProcParentName}}"
          user.domain: "{{user}}"
