name: SEKOIA.IO for Endpoints
pipeline:
  - name: json
    external:
      name: json.parse-json
      properties:
        input_field: '{{original.message}}'
        output_field: event
  - name: fields
stages:
  fields:
    actions:
      - name: set
        set:
          '@timestamp': '{{json.event["@timestamp"]}}'
          action: '{{json.event.action}}'
          agent: '{{json.event.agent}}'
          destination: '{{json.event.destination}}'
          dll: '{{json.event.dll}}'
          dns: '{{json.event.dns}}'
          event: '{{json.event.event}}'
          file: '{{json.event.file}}'
          host: '{{json.event.host}}'
          network: '{{json.event.network}}'
          process: '{{json.event.process}}'
          registry: '{{json.event.registry}}'
          source: '{{json.event.source}}'
          url: '{{json.event.url}}'
          user: '{{json.event.user}}'
          sekoiaio.agent: '{{json.event.sekoiaio.agent}}'
          sekoiaio.host: '{{json.event.sekoiaio.host}}'
          sekoiaio.process: '{{json.event.sekoiaio.process}}'
